### ISSUE TITLE
Feat: improvement in cart section

### ISSUE THREAD

**Issue by sahithinandikula** [Anushkabh/krishiconnect#104]
### Describe the feature

enhancing the color palette and adding hover effect on the details section

since the color of the section is not attractive 
These changes can make the user interaction more smoother

### Add ScreenShots

![Screenshot 2024-05-14 182845](https://github.com/Anushkabh/krishiconnect/assets/138794574/15414c97-a957-48ad-b0e8-d1085f69dd6e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sahithinandikula** [comment]
@Anushkabh I would like to contribute to this issue. considering my request please assign the issue and add label to it

**Comment by sahithinandikula** [comment]
@Anushkabh Thanks! will start working on it

**Comment by vaishnavip27** [comment]
Hey @Anushkabh I would love to work on this issue as a designer and a developer. Please assign me this issue. Looking forward for your approval

**Comment by RitiChandak** [comment]
completed by #128
