### ISSUE TITLE
[FEATURE]: Add Toasts Notification Alert

### ISSUE THREAD

**Issue by yashmandi** [Anushkabh/krishiconnect#106]
### Describe the feature

- In the below page, when user clicks on 'Add to Cart', the user should see a toast notification at the right top corner, which says "Product has been successully added to cart"
- This creates a sense of confirmation to the user that the product has been successfully added to the cart, and user can add more products to cart.
- We should also implement the same notification when the user removes some product from the cart, which will get displayed on the cart page.

I would like to work on this project under GSSOC '24. Request you to kindly assign this task to me ;)

### Add ScreenShots

![Screenshot (202)](https://github.com/Anushkabh/krishiconnect/assets/132436131/abccd35a-d5f8-4d95-a983-bd45181debd0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Explore13** [comment]
I want to work on this feature as a GSSoC'24 Contributor. Please assign it to me.

**Comment by 4086Anupam** [comment]
I want to work this feature  as a part of GSSOC'24 contributor.  please assign at to me .
