### ISSUE TITLE
Feat:Adding dark mode on the pages

### ISSUE THREAD

**Issue by sshivangi882** [Anushkabh/krishiconnect#110]
### Describe the feature

Adding the feature of dark mode on the pages, since many websites have it.

### Add ScreenShots

![Screenshot (866)](https://github.com/Anushkabh/krishiconnect/assets/122531720/e1edea4c-181b-4fd0-b38d-ca692bbec7bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by vaishnavip27** [comment]
Hey @Anushkabh As a designer and a developer. I have experience in building websites. Please assign me this issue. Looking forward for your approval.
