### ISSUE TITLE
Navbar as well as Hero section UI enhancement

### ISSUE THREAD

**Issue by sharmi4590** [Anushkabh/krishiconnect#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh 
The Navbar is overlapping the Hero section and it is very clumsy . I will make sure to change these and make the Hero section more attractive  and even there's icon missing in the buy me I will also add it and make the whole home page responsive for every dimensions.
![Screenshot_20240514-210758](https://github.com/Anushkabh/krishiconnect/assets/102676949/a4d7a8a1-6a87-4ef1-8b46-afcf1938a040)
I will also add some carousels to make it more user friendly. It will make the Hero section more attractive.
Please assign me this , I am GSSoC'24 contributor.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixes #292
