### ISSUE TITLE
Adding social media icons to footer

### ISSUE THREAD

**Issue by Syed0206** [Anushkabh/krishiconnect#118]
### Describe the feature

I would like to add social media icons like LinkedIn,twitter etc to the website @Anushkabh  can you please assign me this issue under GSSOC'24

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-05-15 at 1 06 39 AM" src="https://github.com/Anushkabh/krishiconnect/assets/123359660/8d7aff46-5aa4-450e-acdb-59687b7e6af7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
