### ISSUE TITLE
BUG: Logo not consistent through out the website

### ISSUE THREAD

**Issue by Madhu-mac** [Anushkabh/krishiconnect#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The logo upon the background cover needs to be align with all container items

https://github.com/Anushkabh/krishiconnect/assets/99901964/b54231aa-daf4-4104-9bda-33683a646961

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by Madhu-mac** [comment]
@Anushkabh can you look into this issue, and assign me with GSSoC'24 labels

**Comment by Madhu-mac** [comment]
@Anushkabh I Fixed the issue and raised the PR. it also alignes with #119 So you can merge this PR's without having merge conflicts. Let me know if i need to make any changes

**Comment by Anushkabh** [comment]
@Madhu-mac next time raise pr only for issues that are assigned to you

**Comment by Madhu-mac** [comment]
> @Madhu-mac next time raise pr only for issues that are assigned to you

Actually in #173  , I've raised the issue and also said that im working on it if its assaigned, but you merged smone else PR without assaining to that person..
