### ISSUE TITLE
Improving Readme File Organization and Content

### ISSUE THREAD

**Issue by anshgautam-github** [Anushkabh/krishiconnect#14]
A well-written and organized README is crucial for effectively communicating the value proposition of our project and guiding users and contributors through essential information.

Kindly, assign this issue to me under GSSOC 24

**Comment by aakrati14** [comment]
Please assign this issue to me. I want to work on this issue.

**Comment by Anushkabh** [comment]
@anshgautam-github go ahead .
Make pr within 1 day

**Comment by anshgautam-github** [comment]
@Anushkabh  Thank you for assigning. 
Sure I'll do that !

**Comment by anshgautam-github** [comment]
@Anushkabh  Also I would like to ask, in some issues I have been assigned a level label but here I couldn't see it.
Is the level label important for making the points in the leaderboard?

**Comment by Anushkabh** [comment]
As it's an update to the document, which is a basic change, you'll get 1 point as per the rules.
point system is  given in the contributing.md file, which you can refer to.

**Comment by anshgautam-github** [comment]
@Anushkabh  Okay, thanks for the clarification!
