### ISSUE TITLE
BUG:Cart PAGE IS NOT MOBILE RESPONSIVE AND OVERLAPPING.

### ISSUE THREAD

**Issue by Kratikarajawat70** [Anushkabh/krishiconnect#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening " http://127.0.0.1:5500/krishiconnect-main/cart(1).html" in mobile view its UI is not properly set and navbar also missing.
@Anushkabh ,  I want to work on this issue.

![Screenshot 2024-05-16 151606](https://github.com/Anushkabh/krishiconnect/assets/136308889/7f28dfa3-8f47-4929-8a69-6973dc0c6d9c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@Kratikarajawat70  go ahead .. i am assigning level 3 .. do it properly

**Comment by siddhanttomar2003** [comment]
HI @Anushkabh , I have hands on experience in css , I can make it responsive properly , Plz assign it to me also
