### ISSUE TITLE
Feat:Add Validation during checkout.

### ISSUE THREAD

**Issue by Kratikarajawat70** [Anushkabh/krishiconnect#144]
### Describe the feature

Currently, the checkout form lacks validation, allowing users to enter incorrect or unnecessary details and still place an order. This can lead to errors in order processing and fulfillment. Implementing proper validation will ensure that all required fields are correctly filled out with appropriate information before an order is submitted.

### Add ScreenShots

N/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue under gssoc 24
