### ISSUE TITLE
BUG: Website Title in krishiconnect/login.html

### ISSUE THREAD

**Issue by MastanSayyad** [Anushkabh/krishiconnect#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Add krishiconnect **Website Title** in krishiconnect/login.html 

![image](https://github.com/Anushkabh/krishiconnect/assets/101971980/b0e29e29-97ea-4bf8-ade6-83970068c663)

Could you pls **assign this issue to me under GSSOC'24?**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #146
