### ISSUE TITLE
improving the footer of website

### ISSUE THREAD

**Issue by khushi463-tyagi** [Anushkabh/krishiconnect#15]
Being a Gssoc'24 contributor , I want to contribute in the project by improving the footer of the section by giving equal space between about , links and contact. I hope you assign this issue to me

![Screenshot 2024-05-10 000506](https://github.com/Anushkabh/krishiconnect/assets/66127538/9c2a9a09-4ba2-423d-a69f-fb05b7da5d40)

**Comment by Anushkabh** [comment]
Go ahead @khushi463-tyagi

**Comment by khushi463-tyagi** [comment]
thank you for assigning me

**Comment by parth3083** [comment]
Hey, I am a frontend developer who creates stunning and modern websites.
I completed the internship as a frontend developer.
I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling.
The following are the works where I used lgsap animation and locomotive js :
https://exoape-clone-parth.netlify.app/
https://ochi-clone-parth.netlify.app/

**Comment by dhanushsurendra** [comment]
Hey @Anushkabh, I can improve the footer and make it look better. Could you assign this issue to me?
