### ISSUE TITLE
Nav bar button not aligned in about us tab

### ISSUE THREAD

**Issue by nehashekhawat255** [Anushkabh/krishiconnect#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-16 191047](https://github.com/Anushkabh/krishiconnect/assets/114082299/12be327d-ada0-403d-98ef-ce6470f671b4)
Shop navigation button is not aligned in the same line in about us tab.

please assign this issue to me under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue under gssoc 24
