### ISSUE TITLE
Add Styling to main page

### ISSUE THREAD

**Issue by bhumika-1127** [Anushkabh/krishiconnect#154]
### What's wrong with the existing documentation

Currently the main page doesn't have any styling and is plane black. I wish to work in styling the page under GSSOC'24. @Anushkabh assign me this task.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/137604220/3d156ad3-1544-43c0-9620-0c061f9c7817)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@bhumika-1127  kindly look the  issue i have raised.. solved that first than come here
