### ISSUE TITLE
logo of krishiconnect on navbar going out of the page

### ISSUE THREAD

**Issue by bhumika-1127** [Anushkabh/krishiconnect#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh I can fix this issue under GSSOC'24. Assign me this task
![image](https://github.com/Anushkabh/krishiconnect/assets/137604220/a54fefd0-3dab-49c3-b93d-8141923bb081)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue under gssoc 24

**Comment by himanshu-03** [comment]
Fixed in #182
