### ISSUE TITLE
BUG: Shopping page contents

### ISSUE THREAD

**Issue by bhumika-1127** [Anushkabh/krishiconnect#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The images doesn't align with the headings. @Anushkabh I can fix this under GSSOC'24. Kindly assign me this task.
![image](https://github.com/Anushkabh/krishiconnect/assets/137604220/c0f73fe4-413f-4207-944d-d3bfec271561)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #180
