### ISSUE TITLE
Add to cart Button

### ISSUE THREAD

**Issue by bhumika-1127** [Anushkabh/krishiconnect#157]
### Describe the feature

Add to cart button doesn't give alert on successfully adding the item. @Anushkabh I would like to fix this under GSSOC'24. Assign me this task.

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/137604220/777ccdda-6170-4ca1-a216-c6ba26af5c4f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue under gssoc 24

**Comment by himanshu-03** [comment]
Fixed in #177
