### ISSUE TITLE
Feat: Add Dark mode

### ISSUE THREAD

**Issue by harshmishra19** [Anushkabh/krishiconnect#159]
### Describe the feature

In this feature, I want to add a dark mode option to your website, allowing users to switch the theme from light to dark.

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/115486960/470a43a4-e7d4-4f3d-a003-d23197d3ecd1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by Soumya6Tiwari** [comment]
@Anushkabh  kindly assign me this issue under GSSOC'24.
