### ISSUE TITLE
[Feat]: adding light mode / dark mode option 

### ISSUE THREAD

**Issue by souvik-maity** [Anushkabh/krishiconnect#16]
Kindly assign this to me.I am eagerly waiting to contribute to this project.

**Comment by Anushkabh** [comment]
what's the update? @souvik-maity

**Comment by souvik-maity** [comment]
Kindly give me 2 more days time as my end semester exams are going on.I will complete it by Tuesday. I hope that you understand and give a positive response.

**Comment by Akshatakapare** [comment]
I would like to add a light mode/dark mode option with an attractive icon. Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by souvik-maity** [comment]
@Anushkabh I am getting an error when I am trying to clone the forked repository. I have tried it multiple times but still the issue is there. Kindly look into it ,I shall be grateful for your help.
![Screenshot 2024-05-14 195417](https://github.com/Anushkabh/krishiconnect/assets/145227417/25a255dc-0b0d-4637-a2f3-abd923f85fb4)

**Comment by himanshu-03** [comment]
@souvik-maity can you please mention your Pull Request here?
