### ISSUE TITLE
BUG: THe loader is persistent , because of this home page is not visible  

### ISSUE THREAD

**Issue by Anushkabh** [Anushkabh/krishiconnect#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-17 083445](https://github.com/Anushkabh/krishiconnect/assets/99523033/53c4ca75-941c-47cd-be5e-752555c3a601)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue . please assign me under gssoc2024

**Comment by nishant0708** [comment]
thank you for assigning me this issue i will soon raise pr

**Comment by himanshu-03** [comment]
Fixed in #169
