### ISSUE TITLE
Improve the UI of Contact Us page 

### ISSUE THREAD

**Issue by souravgope** [Anushkabh/krishiconnect#168]
### Describe the feature

before the contact page background image is not match according to the organization .
![WhatsApp Image 2024-05-17 at 12 35 17_eb7bf4ad](https://github.com/Anushkabh/krishiconnect/assets/137763197/be318e42-be94-4a16-8d68-b42b6e4a086e)

### Add ScreenShots

further i will  the improve UI of this project according to organisation theme 
![Screenshot (176)](https://github.com/Anushkabh/krishiconnect/assets/137763197/86a17ef3-6df2-47d3-adcf-d860cf28aa09)
please assignm me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souravgope** [comment]
accept the PRs

**Comment by souravgope** [comment]
hey @Anushkabh i did it please accept the Pull request

**Comment by souravgope** [comment]
hey @Anushkabh  please accept the prs

**Comment by RitiChandak** [comment]
completed by #186

**Comment by himanshu-03** [comment]
Fixed by #186
