### ISSUE TITLE
Feat:CUSTOMIZING FOOTER

### ISSUE THREAD

**Issue by Nih1tGupta** [Anushkabh/krishiconnect#170]
### Describe the feature

FOOTER IS SIMPLE AND NOT ATTRACTIVE

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/119615342/688890b2-6380-4ccc-bd7c-bb4f99dc8607)
1.Adding a background imge
2.improving font-weight.
3.Hover effect/transition can be added

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue under gssoc 24

**Comment by Nih1tGupta** [comment]
Thanks @Anushkabh for assigning me.

**Comment by Nih1tGupta** [comment]
PLEASE SEE MY PR : #207
