### ISSUE TITLE
Feat: Improve the UI of enter the details section

### ISSUE THREAD

**Issue by Anou25** [Anushkabh/krishiconnect#174]
### Describe the feature

The UI of the details section is not so appealing so by implementing proper font and color it can be made more visually attractive.

@Anushkabh please assign this to me

### Add ScreenShots

![Screenshot 2024-05-17 221517](https://github.com/Anushkabh/krishiconnect/assets/136624807/e7ab11c4-d30f-45b9-ac84-a4f072765267)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anou25** [comment]
Thanks but kindly can you please assign it to me

**Comment by Wafmulla** [comment]
Can you please assign this issue to me under gssoc24 label

**Comment by himanshu-03** [comment]
Fixed in #283
