### ISSUE TITLE
FIX: Need to update the login and signup card

### ISSUE THREAD

**Issue by Madhu-mac** [Anushkabh/krishiconnect#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login & signup card in the website is not relevant to the website and also there's no pointing when we try too click on the signup & login contents 

https://github.com/Anushkabh/krishiconnect/assets/99901964/63b11916-395c-4d6c-b353-41a22563eaa4

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
@Bhavishya2602 its not assaigned to you! i mentioned there im currently working on this..

**Comment by Madhu-mac** [comment]
> @Bhavishya2602 its not assaigned to you! i mentioned there im currently working on this..

@Anushkabh You forgot to assign the issue to me..

**Comment by shifa-s11** [comment]
@Anushkabh please assign this issue to me i would do my best 
here is the demo login page 
![Screenshot (39)](https://github.com/Anushkabh/krishiconnect/assets/144918231/7db783b0-da9a-420f-8962-9122ad14a0c2)

**Comment by Yuvraj960** [comment]
@Anushkabh Please assign this issue to me under GSSoC24

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24 @Anushkabh

**Comment by Hemu21** [comment]
@Anushkabh  can you please assign this to me

**Comment by SujalRaunak** [comment]
@Anushkabh I can do this better, with good user experience design. Kindly assign this to me.
I have experience of creating UI with good UX.
