### ISSUE TITLE
Feat: Need to improve the layout of the login and sign up page

### ISSUE THREAD

**Issue by Bhavishya2601** [Anushkabh/krishiconnect#188]
### Describe the feature

Your webpage current signup Card is somewhat like this
![Screenshot 2024-05-18 100538](https://github.com/Anushkabh/krishiconnect/assets/147748752/6815f0c4-3af5-41ce-a279-2c4602551d87)
I wanna change it because it looks kind of unprofessional and doesn't have much styling to it 
I wanna change it to something like this (this is a reference, the color combinations and some details with be according to your webpage), the background image with be also changed to something farmer based.
![Screenshot 2024-05-18 100551](https://github.com/Anushkabh/krishiconnect/assets/147748752/a01dda5b-00ee-404c-b937-fc5e00ef9017)

### Add ScreenShots

![Screenshot 2024-05-18 100551](https://github.com/Anushkabh/krishiconnect/assets/147748752/1dd9963d-8522-4468-b1bf-0528c8152c1e)
(The above screenshot is from my recent project.)

Hope you would assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #189
