### ISSUE TITLE
Feature : Adding arrow button to quickly move to the top

### ISSUE THREAD

**Issue by Ratnesh-Rajput** [Anushkabh/krishiconnect#20]
Feature Details:
I have an idea of adding a arrow button for quickly moving to the top without scrolling

Code of Conduct
 I agree to follow this project's Code of Conduct

**Comment by Ratnesh-Rajput** [comment]
Please assign this issue to me.
@Anushkabh

**Comment by dipanjanchoudhury** [comment]
I feel i can work on this issue as i have already completed full stack web development and i have many more ideas how we can make it  more user friendly and attractibve as well following the project's code of conduct
