### ISSUE TITLE
Feat: Redesign the whole UI and make it more responsive and fix all the UI and UX related bugs.

### ISSUE THREAD

**Issue by prateek-workspace** [Anushkabh/krishiconnect#201]
### Describe the feature

1. Seperate all the pages like About, Contactus etc.
2. Fixing UI and making it better.
3. Making UI responsive.
4. Adding Login and logout pages along with the user profile page.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
raise prs one by one

**Comment by prateek-workspace** [comment]
Okay I'll start working on it from today 👍

**Comment by prateek-workspace** [comment]
By tomorrow, I will send a demo homepage. If you agree, I will start working on it. If not, I'll make some changes and ask for your review again.

**Comment by prateek-workspace** [comment]
Hey there,

Below are the screenshots of the work I did. If you like them, I will continue working on this design. If you have any suggestions, please let me know.

I also want to mention that this design is not solely mine. It is an open-source template that anyone can use freely without any restrictions. I am modifying it to fit this project.

Looking forward to your feedback!

![Screenshot (55)](https://github.com/Anushkabh/krishiconnect/assets/110523559/5d26e781-aff6-44f5-a754-8eaf422f4ef7)
![Screenshot (56)](https://github.com/Anushkabh/krishiconnect/assets/110523559/e8337d01-3f2e-4253-bc56-45d68c1d62aa)
![Screenshot (57)](https://github.com/Anushkabh/krishiconnect/assets/110523559/de0a9496-0fc8-4783-bd45-c23887d96b7e)

**Comment by prateek-workspace** [comment]
What you think guys....should i carry on this design?
