### ISSUE TITLE
Feat:added item in cart once but showing twice

### ISSUE THREAD

**Issue by kapilG0** [Anushkabh/krishiconnect#213]
### Describe the feature

Added item in cart once but showing twice in my cart

### Add ScreenShots

![Screenshot_20240518_230307](https://github.com/Anushkabh/krishiconnect/assets/59639410/e136919f-6a2a-46e5-b6ca-6321dd59e88f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @Anushkabh please assign this issue to me under gssoc 24

**Comment by nishant0708** [comment]
Hey assign me this issue

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
