### ISSUE TITLE
BUG: Changing twitter icon

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I observed that twitter logo was not changed in the footer section.
I want to work on this issue.
Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aasthabagrawal** [comment]
I would love to work on this.
