### ISSUE TITLE
Feat: Improving styling of social media icons

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#241]
### Describe the feature

In footer ,the social media links are not properly styled.
so i want to style them and add hover effects so that they look atrractive.
@Anushkabh please assign this issue to me under GSSOC 2024 and add appropriate labels to it.

### Add ScreenShots

![Screenshot 2024-05-20 131836](https://github.com/Anushkabh/krishiconnect/assets/169278740/54557eed-3348-4377-ab19-c33b2a51e027)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varshajha5** [comment]
@Anushkabh please assign this issue to me under gssoc 2024

**Comment by aasthabagrawal** [comment]
Plz assign this task to me.

**Comment by himanshu-03** [comment]
Fixed in #306
