### ISSUE TITLE
Feat: Improving Footer

### ISSUE THREAD

**Issue by SrijaVuppala295** [Anushkabh/krishiconnect#243]
### Describe the feature

Footer is not in the proper way!!! The social media icons should be given proper spacing. And the title in the footer not bold and visible. Improving it looks more attractive.

### Add ScreenShots

![Screenshot (117)](https://github.com/Anushkabh/krishiconnect/assets/140592148/0ffbde0d-e2cf-4cdf-9e50-699d71fce280)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aasthabagrawal** [comment]
Plz assign this task to me under GSSOC.

**Comment by meenakshiiyer2531** [comment]
Hey @Anushkabh 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer
