### ISSUE TITLE
DOC: Changing the rupees icon

### ISSUE THREAD

**Issue by SrijaVuppala295** [Anushkabh/krishiconnect#244]
### What's wrong with the existing documentation

The cost of the vegetables are not showing the proper icon to describe its price. I want to add the rupees symbol.

### Add ScreenShots

![Screenshot (120)](https://github.com/Anushkabh/krishiconnect/assets/140592148/4a375f6b-54b5-4953-a758-e0c5ab4e4fc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
Please assign this issue to me.
\assign

**Comment by aasthabagrawal** [comment]
I would love to solve the issue. Plz assign this task to me.

**Comment by himanshu-03** [comment]
Fixed in #536
