### ISSUE TITLE
Feat: Improve the navbar

### ISSUE THREAD

**Issue by SrijaVuppala295** [Anushkabh/krishiconnect#246]
### Describe the feature

The shop page doesnt have the icon on the navbar. And in many pages icon is not visible for shop in the navabar.

### Add ScreenShots

![Screenshot (123)](https://github.com/Anushkabh/krishiconnect/assets/140592148/85765445-52dd-46aa-ab5b-b151df0f581a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
Please assign this issue to me

**Comment by aasthabagrawal** [comment]
Plz assign this task to me.
