### ISSUE TITLE
BUG:white text in white background

### ISSUE THREAD

**Issue by Varsani2520** [Anushkabh/krishiconnect#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh ,
display white text in white background:
![image](https://github.com/Anushkabh/krishiconnect/assets/137641079/fa38046d-654e-4bae-9b07-eada504412a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 22-0304** [comment]
Can you assign me this issue @Anushkabh
