### ISSUE TITLE
Feat: Detailed Page is Missing

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#257]
### Describe the feature

@Anushkabh 

Please check this, there are no detailed page for vegitables, fruits etc...

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/7c8b5b4b-36b4-489c-8b9c-ae99dc0aa390)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
@Anushkabh Thank you

**Comment by himanshu-03** [comment]
Fixed in #308
