### ISSUE TITLE
improving the cart ui

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#26]

**Comment by pandeyji711** [comment]
Hello @Suchitra-Sahoo,

I've noticed an issue with the website , I have work on UI/UX before (project is in my github) Could you please assign this issue to me for contribution under GSSoC'24?

**Comment by himanshu-03** [comment]
Hey @pandeyji711,

Can you please provide with the screenshots of the UI you are willing to change or modify?
