### ISSUE TITLE
Enhancement in the UI of Contact section

### ISSUE THREAD

**Issue by shrutigolwalk0109** [Anushkabh/krishiconnect#267]
### Describe the feature

It looks better if we make some changes in the contact form and enhance its UI. Right Now it looking different from the rest of the Website.
Please assign this Issue to me with the Label of GSSOC. I want to work on it.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/132553685/b6df631d-4284-458b-860b-824ed55a24c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
@Anushkabh 

My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design a immersive contact us page ,
(adding google map integration if wanted)

Please assign this task to me, GSSOC'24 .
