### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#27]

**Comment by VedaVarxha** [comment]
@Anushkabh I would like to work on this issue under GSSOC'24. Please assign it to me

**Comment by Anushkabh** [comment]
@VedaVarxha raise a separate issue for this. I'll then assign you

**Comment by himanshu-03** [comment]
Dear @anuza08,

I hope this message finds you well.

I am writing to inform you that the issue you raised has already been addressed. After a thorough review and consideration, we have implemented the necessary changes to resolve the matter.

We appreciate your patience and understanding throughout this process. Should you have any further concerns or require additional information, please do not hesitate to reach out.

Thank you for bringing this to our attention and for your continued support.
