### ISSUE TITLE
improving ui of farmer's login page

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#28]

**Comment by Deathnote45** [comment]
hi, I want to contribute on this issue under gssoc'24

**Comment by Karthikeyan1508** [comment]
Hey @Anushkabh !!
I can improve the UI of the Login Page.
Can you assign me to this issue under GSSoC'24...?

**Comment by pulkit49** [comment]
I can create a vibrant UI if you assign me under GSSOC 2024.

**Comment by himanshu-03** [comment]
Hello!

Anyone who is interested in working under this issue can attach the screenshots of the modified design.
