### ISSUE TITLE
adding navbar to farmer's login page 

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#29]
there is not option to go on home page from farmer's login page

**Comment by Hardikchandra** [comment]
can you please add level to this issue.
 want to work on this issue .

**Comment by himanshu-03** [comment]
Dear @anuza08,

I hope this message finds you well.

I am writing to inform you that the issue you raised has already been addressed. After a thorough review and consideration, we have implemented the necessary changes to resolve the matter.

We appreciate your patience and understanding throughout this process. Should you have any further concerns or require additional information, please do not hesitate to reach out.

Thank you for bringing this to our attention and for your continued support.
