### ISSUE TITLE
Feat: Table for transactions page

### ISSUE THREAD

**Issue by Bhavishya2601** [Anushkabh/krishiconnect#299]
### Describe the feature

I want to create a transaction table on transaction page which will tell the transactions made by the person

Hope you would assign this task to me

### Add ScreenShots

![Screenshot 2024-05-24 120649](https://github.com/Anushkabh/krishiconnect/assets/147748752/1dd2bcf5-2710-44ac-bf34-7554dab5c055)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
@Bhavishya2601  can you please mention your Pull Request here?
