### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by sanjay-kv** [Anushkabh/krishiconnect#3]
As the maintainer of a Collaborate repo, keeping Issues up-to-date will help the student community understand what they can do to contribute. Issues should vary by the easy (update documentation) to the difficult (add a new feature). The more involved you are, the more opportunities there are to collaborate.

Recommendations:

Add issues of varying difficulty to the repo often. you can add the tag GSSoC'24, good first issue etc.
Generate issues even if you plan on solving them, so the repository appears as active.
Contribute/commit often to the repo so it does not go stale.

Reference https://github.com/Recode-Hive/Stackoverflow-Analysis/issues

**Comment by Satyaas1117** [comment]
I want to contribute in your project some areas need improvement like:
1. there should be hover effect on icons 
2. there should some space on text (why krishi connect)
3. there need some colour in sq box for more effectiveness 
please could you assigned it to me?
![krishi1](https://github.com/Anushkabh/krishiconnect/assets/152584509/ebe1042f-1807-4566-bec3-d7f371dcc2bf)
