### ISSUE TITLE
Making the navbar logo clickable

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#30]

**Comment by am-1145** [comment]
Please assign me this issue

**Comment by pandeyji711** [comment]
Hello @Anushkabh ,

I've noticed an issue with the website that I believe I can fix. Could you please assign this issue to me for contribution under GSSoC'24?

**Comment by hritika2409** [comment]
https://github.com/Anushkabh/krishiconnect/assets/117531823/d2301cfd-6bb3-480b-be68-8fdd3e247c1b

I can work on this as i have already addressed this issue on my site

**Comment by himanshu-03** [comment]
Dear @anuza08 
I hope this message finds you well.

I am writing to inform you that the issue you raised has already been addressed. After a thorough review and consideration, we have implemented the necessary changes to resolve the matter.

We appreciate your patience and understanding throughout this process. Should you have any further concerns or require additional information, please do not hesitate to reach out.

Thank you for bringing this to our attention and for your continued support.
