### ISSUE TITLE
BUG:EXTRA NAVBAR ICON IN WISHLIST PAGE

### ISSUE THREAD

**Issue by Nih1tGupta** [Anushkabh/krishiconnect#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/119615342/1cc12675-be7c-43e4-9b03-a658ebec6bcf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by Nih1tGupta** [comment]
@Anushkabh please assign the label
