### ISSUE TITLE
Feat: Include Forgot Password In Log-In.

### ISSUE THREAD

**Issue by kiruthigaa-k** [Anushkabh/krishiconnect#305]
### Describe the feature

The forgot password is not included in the login page. It is better to add this feature to users who forgot the password and it navigate to the page where the user can change the new password.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/112771633/3a2a5558-01dc-49b5-a495-a769bca5ecb3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sneha0019** [comment]
I can make forgot password page where user will be asked input for his old password and new password and then this data will be update in backend. Please assign this to me!

**Comment by Sneha0019** [comment]
I can make forgot password page where user will be asked input for his old password and new password and then this data will be update in backend. Please assign this to me!
