### ISSUE TITLE
BUG: Changing twitter logo in footer section

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Twitter logo in footer section is incorrect.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hey @Anushkabh 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer
