### ISSUE TITLE
Creating contact us page.

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#314]
### Describe the feature

I observed that there is no contact page in web page.
I want to add it.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hey @Anushkabh 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer
