### ISSUE TITLE
Documentation can be better.

### ISSUE THREAD

**Issue by Shreyaa173** [Anushkabh/krishiconnect#325]
### What's wrong with the existing documentation

It is not appropriate. 
![Screenshot 2024-05-25 151317](https://github.com/Anushkabh/krishiconnect/assets/144673309/53a72fcf-ec22-4b61-b3a6-9b6dd4b441a4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hey @Anushkabh 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer
