### ISSUE TITLE
Feat: Enhance FAQ Section

### ISSUE THREAD

**Issue by Hemashree21** [Anushkabh/krishiconnect#326]
### Describe the feature

The current FAQ has a very less font size and it's also not responsive. I can work on this and make it more visually appealing and responsive.

@Anushkabh can you please assign this to me?

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/138188163/c9edf652-20bc-4874-9dfb-7dcfb4eacab6)

![Screenshot 2024-05-24 212548](https://github.com/Anushkabh/krishiconnect/assets/138188163/6c4063d1-4c67-4afd-94f0-91b40b9f54fc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hey @Anushkabh 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer

**Comment by himanshu-03** [comment]
Fixed in #335
