### ISSUE TITLE
alert when item added in cart

### ISSUE THREAD

**Issue by aditi-tyagi02** [Anushkabh/krishiconnect#33]
When the items are added, they don't show alert so added to cart message can be displayed.

**Comment by debasmi** [comment]
kindly assign me this issue

**Comment by pandey079** [comment]
Please assign it to me under GSSOC'24.

**Comment by ankita685** [comment]
![img1](https://github.com/Anushkabh/krishiconnect/assets/99496688/beca6beb-2e23-4d9e-aeba-0bc20520f519)
![img2](https://github.com/Anushkabh/krishiconnect/assets/99496688/63b88b1c-f036-4079-8083-024376c682e6)
I have successfully completed the task adding alert option when add to cart button clicked
