### ISSUE TITLE
BUG: FOOTER UI IN WISHLIST 

### ISSUE THREAD

**Issue by Nih1tGupta** [Anushkabh/krishiconnect#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/119615342/0c5c7120-726e-45b1-9e5b-16b06ec60962)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
you want to change it?

**Comment by Nih1tGupta** [comment]
Yes, Font-size,color,family and socila media icons css and font-width..etc

**Comment by Nih1tGupta** [comment]
It can be improved , @Anushkabh ,I want to work on this
