### ISSUE TITLE
Redesign Testimonals Section

### ISSUE THREAD

**Issue by Hemashree21** [Anushkabh/krishiconnect#342]
### Describe the feature

The testimonals section is not visible completely when it's hovered and also not responsive in mobile view. I want to work on this and enhance it. I will make it responsive across all devices.

@Anushkabh can you please assign this to me?

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/138188163/7f3a32c0-4a4b-4d3d-ae2e-6cd25740e345)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
@Hemashree21 ! are you still interested in working oon this issue. If not this issuee will be closed in 2 days.

**Comment by Hemashree21** [comment]
@himanshu-03 Hello sir, can you please assign it to someone else? Sorry for the inconvinience

**Comment by himanshu-03** [comment]
okay!
