### ISSUE TITLE
BUG:In mobile the hamburger menu is at different positions

### ISSUE THREAD

**Issue by Rohitha-pudu** [Anushkabh/krishiconnect#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the hamburger menu is not responsive and is located at different positions in different pages ,and also the menu items are looking different in different pages,there is no consistent one
![image](https://github.com/Anushkabh/krishiconnect/assets/116823590/635ada47-9589-475a-9676-6059352b1e6d)
![image](https://github.com/Anushkabh/krishiconnect/assets/116823590/3312dc37-fe47-460a-b793-90a519229055)
![image](https://github.com/Anushkabh/krishiconnect/assets/116823590/8d209be8-755f-4cd0-8c72-eb4dd6207a5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #374
