### ISSUE TITLE
BUG: Year needs to update dynamic instead of static

### ISSUE THREAD

**Issue by kapilG0** [Anushkabh/krishiconnect#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/59639410/71ff9b1c-a8dd-4ac1-84a3-ccb3b60ce32c)
As you can see in elements 2024 static value is passed 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @Anushkabh please assign this issue to me under gssoc 24

**Comment by Anushkabh** [comment]
this is solved i guess
