### ISSUE TITLE
[Feature]: Develop Service page

### ISSUE THREAD

**Issue by Vaibhavsg17** [Anushkabh/krishiconnect#35]
Description:
This pull request introduces a new feature to KrishiConnect that enhances our commitment to supporting farmers by offering soil-testing and water-testing services. These services aim to empower farmers with valuable insights into the health and quality of their agricultural resources, ultimately helping them optimize their farming practices and increase production.

Changes:

New Page Addition: Added a new page to the KrishiConnect website titled "Soil & Water Testing Services."
Page Content: Included detailed information about the soil-testing and water-testing services offered, highlighting their importance for farmers and the benefits they provide.
Service Descriptions: Provided descriptions of both soil-testing and water-testing services, outlining the parameters tested and the insights provided to farmers.
Benefits Section: Included a section highlighting the benefits of utilizing these services, such as improved crop yields, resource optimization, and sustainable farming practices.
Call-to-Action: Added a call-to-action section encouraging farmers to take advantage of these services and providing a link to contact our team for more information or to schedule testing.

**Comment by Vaibhavsg17** [comment]
Additional Notes:
This feature aligns with our mission to revolutionize the agriculture sector and empower farmers with the tools and resources they need for success. By offering soil-testing and water-testing services, we are furthering our commitment to supporting sustainable farming practices and promoting economic prosperity for our farmer friends.

**Comment by Vaibhavsg17** [comment]
@Anushkabh assign this to me

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
