### ISSUE TITLE
Feat::Same Navbar on All Pages

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#354]
### Describe the feature

There is a issue that home page and other pages have different Navbar

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/368e19e4-428d-4684-b832-d0bc1512c9f8)
![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/67950b67-dd5f-4e23-b09e-d326dbe14860)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #383
