### ISSUE TITLE
Feat: Creating a Node.js backend for the website

### ISSUE THREAD

**Issue by sambitsingha** [Anushkabh/krishiconnect#357]
### Describe the feature

The website needs a backend for proper functionality of new features which works only with the help of a backend. I would like to work on building a Node.js based backend using Express.js and converting the .html files into .ejs files for integrating it with the Express.js server.

### Add ScreenShots

No screenshot applicable.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@sambitsingha  I was looking for someone to do this. Please break your work and raise it part-wise. go ahead.

**Comment by sambitsingha** [comment]
@Anushkabh Hey so , first of all I will arrange the files into proper folders for better nagivation and initialise the Express server. This will be the first PR. Second , I will change the .html files to .ejs files aand integrate it with the Express server and this will be PR 2. 

So in total , I will raise 2 PRs for this issue. Kindly add the level 3 for both of them. Thank you :)

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!
