### ISSUE TITLE
Footer can be improved. 

### ISSUE THREAD

**Issue by anshmanitripathi** [Anushkabh/krishiconnect#36]
In footer the phone icon is inappropriate this should be fixed.
![Screenshot (73)](https://github.com/Anushkabh/krishiconnect/assets/143960008/7c286f50-9b5a-4cd1-8029-685414e7f4cd)

**Comment by anshmanitripathi** [comment]
I want to work upon this , Please assign this task to me under GSSOC 2024.

**Comment by aakrati14** [comment]
Please add labels.

**Comment by hritika2409** [comment]
I would like to work on this please assign me this task

**Comment by tushant-akar** [comment]
@Anushkabh Please assign this problem to me.
I am eager to contribute to the above issue

**Comment by himanshu-03** [comment]
@anshmanitripathi  can you please mention your Pull Request here?
