### ISSUE TITLE
back to top button is changing its positions while clicking

### ISSUE THREAD

**Issue by Ketanop321** [Anushkabh/krishiconnect#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we click on back to top button its positions get changes 

https://github.com/Anushkabh/krishiconnect/assets/146806880/4e0b0fd2-fd87-416e-9cae-53272bfb836d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SujalRaunak** [comment]
@Anushkabh assign this to me
