### ISSUE TITLE
BUG: UI/UX Improvement in Cart.html

### ISSUE THREAD

**Issue by aarushi-taori** [Anushkabh/krishiconnect#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

UI/UX Improvement in Cart.html

![image](https://github.com/Anushkabh/krishiconnect/assets/113369937/2892263d-bd2e-4b7e-bb01-c0f45d40deeb)
![image](https://github.com/Anushkabh/krishiconnect/assets/113369937/75d80c23-21cd-4bda-b7ec-9002a1e03153)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aarushi-taori** [comment]
@Anushkabh Please assign me this issue

**Comment by PrakarshSingh5** [comment]
Please assign this task to me

**Comment by Suruchibharti** [comment]
hiii @aarushi-taori  , I want to work on this issue please assign me
