### ISSUE TITLE
BUG: UI/UX Improvement of Footer in wishlist.html

### ISSUE THREAD

**Issue by aarushi-taori** [Anushkabh/krishiconnect#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

UI/UX Improvement of Footer in wishlist.html

![image](https://github.com/Anushkabh/krishiconnect/assets/113369937/3a8bcc06-15cb-456e-bd4e-6ba56421de30)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
@aarushi-taori  can you please mention your Pull Request here?

**Comment by RitiChandak** [comment]
completed by #453

**Comment by RitiChandak** [comment]
@aarushi-taori From next time please mention issue no in the PR
