### ISSUE TITLE
BUG: Social media websites not linked in footer

### ISSUE THREAD

**Issue by sanyaP19** [Anushkabh/krishiconnect#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The social media icons given in the footer are not linked.
Each icon, when clicked does not shows the social media profile!
![image](https://github.com/Anushkabh/krishiconnect/assets/78594569/a4c557a3-a167-485c-9fa6-fdbb6a3fff50)

After clicking the icons, the address goes invalid
![image](https://github.com/Anushkabh/krishiconnect/assets/78594569/792d1619-d509-4ca4-95a3-0506c8fb20f6)

@Anushkabh, Kindly assign this issue to me, I want to work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanyaP19** [comment]
@Anushkabh, do you want me to make new profiles on social media for KrishiConnect ? If the profiles are already made, could you please send me their links?

**Comment by KavyaBS123** [comment]
Hey @RitiChandak can you please assign this issue to me I would be glad to work on it!
