### ISSUE TITLE
BUG: Darkmode icon issue in another pages

### ISSUE THREAD

**Issue by HK853** [Anushkabh/krishiconnect#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/113816862/1738dcec-186f-489b-84e7-a79ef095d40f)
Assign me this issue under GSSoC with level. I want to fix this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it.
