### ISSUE TITLE
BUG: Overflowing text: Why KrishiConnect Cards

### ISSUE THREAD

**Issue by aarushroyy** [Anushkabh/krishiconnect#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The home page cards present under "Why KrishiConnect" have overflowing text. Makes them unreadable plus unappealing.

![image](https://github.com/Anushkabh/krishiconnect/assets/69352438/8e7cc385-200a-4280-abca-a4f539bf16ff)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it.

**Comment by aarushroyy** [comment]
@RitiChandak the issue been fixed already? While there was no issue like this earlier? can you please make sure this doesn't happen again? This is very unprofessional :(
