### ISSUE TITLE
BUG: Navbar Items - Not Aligned

### ISSUE THREAD

**Issue by aarushroyy** [Anushkabh/krishiconnect#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar items for all the pages except the home are not aligned. Too much right centred or taking double-line unwanted space. 

![image](https://github.com/Anushkabh/krishiconnect/assets/69352438/8b1289a9-47bb-47a2-8e21-3c59e22d8490)
![image](https://github.com/Anushkabh/krishiconnect/assets/69352438/44a37efc-f63e-471c-94c3-ff2849520a81)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KavyaBS123** [comment]
Hey @RitiChandak I am GSSOC contributor can you please assign this issue to me I would be glad to work on it!
