### ISSUE TITLE
Feat: Adding animations to the Cursor

### ISSUE THREAD

**Issue by harshmishra19** [Anushkabh/krishiconnect#379]
### Describe the feature

I want to add some animations while moving the cursor over the website, and clicking a button. This feature will surely enhance the website, and ensure an improved User experience.

### Add ScreenShots

I don't have screenshots right now, because I've not implemented it yet, but if assigned, I can assure not to disappoint you by any chance.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshmishra19** [comment]
I think you forgot to add label @Anushkabh @RitiChandak

**Comment by RitiChandak** [comment]
@harshmishra19 Don't worry about that we will add it at the time of pr after seeing your work

**Comment by harshmishra19** [comment]
Oh ok, I have made the PR

**Comment by RitiChandak** [comment]
Okay let me check it
