### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by sonakshisonkusare** [Anushkabh/krishiconnect#380]
The footer is too large in the size by doing some essential changes and by putting logo's at the proper places the footer can be enhanced i  want to work on this issue.
please assign me this issue....

**Comment by RitiChandak** [comment]
@sonakshisonkusare This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!

**Comment by sonakshisonkusare** [comment]
Thank you for your feedback! I will check the existing issues and make sure not to duplicate any. I'll look for another issue or feature to contribute to. Appreciate your guidance!
