### ISSUE TITLE
Feat: Are you a buyer? Link on seller page

### ISSUE THREAD

**Issue by MitulSonagara** [Anushkabh/krishiconnect#384]
### Describe the feature

As on dashboard there is a link for are you a seller? If someone goes to seller page and then want to go back to buyer page then there is no link for that. I will make it.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/95460188/c6107e76-a5d1-4aa2-94b7-a4fbb8d2b724)

![image](https://github.com/Anushkabh/krishiconnect/assets/95460188/f4695909-6c6e-4ab2-9772-9fc3a3edfd40)
In this here should be Are you buyer? link

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@MitulSonagara Assigned!
