### ISSUE TITLE
BUG: Product image is not there

### ISSUE THREAD

**Issue by MitulSonagara** [Anushkabh/krishiconnect#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In main page of website there is a missing image of tomato.

![image](https://github.com/Anushkabh/krishiconnect/assets/95460188/201d6e58-31f0-49c3-8940-b9626efe10f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@MitulSonagara Assigned !!
