### ISSUE TITLE
BUG: Navbar issue on seller page

### ISSUE THREAD

**Issue by MitulSonagara** [Anushkabh/krishiconnect#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If i shrink size to mobile there is a problem in hamburger menu.
![image](https://github.com/Anushkabh/krishiconnect/assets/95460188/fab863a0-8fd9-4530-89b7-9b4315454b89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new  one. Find another issue or feature to contribute to. Thank you!
