### ISSUE TITLE
Feat:  Enhance Responsive ANIMATION and hover effect in WHY कृषिCONNECT

### ISSUE THREAD

**Issue by Husan7** [Anushkabh/krishiconnect#388]
### Describe the feature

I would like to work on this issue(feature)
By adding this feature WHY कृषिCONNECT looks more attractive .
It's a Responsive animation and effect 

### Add ScreenShots

DESKTOP MODE

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/a006c615-193f-47e5-8098-2b7ff45d6adb

MOBILE MODE

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/2fa842ae-841d-4a5a-827e-93e61eb097d0

Please ASSIGN me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #395

**Comment by Husan7** [comment]
@Anushkabh 
@RitiChandak 
@himanshu-03 
Hi sir , 
My this PR is merged about  2months ago but  points of this PR is not showing my GSSoC'24 Leaderboard  
May be it's because you marked as close after merging 
Sir , please solve this issue so I can see my score on leaderboard of this PR .

Thanks
