### ISSUE TITLE
BUG: Redirect to Email in the footer section

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anushkabh/krishiconnect#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in the footer if anyone click upon the mail then he/she can redirect to the email to direct send the mail
![image](https://github.com/Anushkabh/krishiconnect/assets/125277258/f66f6fce-aba0-4f15-96ad-b8c6429e5bb8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@RamakrushnaBiswal Assigned!

**Comment by RamakrushnaBiswal** [comment]
@RitiChandak please review the PR #403
