### ISSUE TITLE
Enhance the Effect

### ISSUE THREAD

**Issue by sonakshisonkusare** [Anushkabh/krishiconnect#397]
https://github.com/Anushkabh/krishiconnect/assets/133730255/1968ee18-cb0f-4eb5-97ce-7d8b909ec416

I would like to  improve this and make it smooth so that the user experience gets improve.

**Comment by sonakshisonkusare** [comment]
please assign me this issue

**Comment by amruthaduvvuri** [comment]
Please assign me the issue in order to provide a better outcome of the website
