### ISSUE TITLE
BUG: wrong file name for contact.html

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello 
I have found that when we click on contact us page it shows 404 page not found error 
![Screenshot_2024-06-01-13-36-23-28_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Anushkabh/krishiconnect/assets/169278740/3c6a74fe-ec8f-42d9-8e8d-3403dfd73095)
Actually this is due to wrong file name.
![IMG_20240601_133612](https://github.com/Anushkabh/krishiconnect/assets/169278740/bea67b24-d647-4533-a91e-4f8010c81eb1)
As we can see it seems Contact(1).html ..but it should be contact(1).html.

@Anushkabh please assign this issue to me under GSSOC 2024 and add necessary labels to it 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SalehaTabassum Assigned

**Comment by himanshu-03** [comment]
Fixed in #445
