### ISSUE TITLE
Adding Hovering Effect to the Cards

### ISSUE THREAD

**Issue by kamalesh-og** [Anushkabh/krishiconnect#40]
Hello @Anushkabh ,
I wanted to solve an enhancement issue for this page by adding hover effects for all the card components in the Shop Page on the webpage, excluding the footer. Additionally, i wanted to refactor some CSS of the cards by adding borders to improve readability and maintain consistency.

![image](https://github.com/Anushkabh/krishiconnect/assets/163159351/a0ae6bd6-7d62-40cd-9ca6-b1be08da1fde)
This is the reference image I would like to attach for the cards i want to apply the hovering and make it look proper

Can you please assign me this issue, I'd be delighted to work on this.
Thank You.

**Comment by kamalesh-og** [comment]
Thank You @Anushkabh

**Comment by kamalesh-og** [comment]
should I consider resolving it further? because someone already merged it

**Comment by himanshu-03** [comment]
Fixed in #93 and #309
