### ISSUE TITLE
BUG: Shop page footer contact part hover effect

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anushkabh/krishiconnect#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/125277258/2cea70f4-2c38-4e30-82c7-a57aab7a5327)
Shop page footer contact part hover effect not applied properly

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Fixed in #488
