### ISSUE TITLE
BUG: Dark mode button is not designed correctly. Whole nav bar looks bad. Needs right spacing

### ISSUE THREAD

**Issue by ZayedShahcode** [Anushkabh/krishiconnect#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On non homepage pages the dark mode button doesn't look good, its out of container. Nav bar looks bad. Assign it to me. I will fix it quickly

![image](https://github.com/Anushkabh/krishiconnect/assets/115407231/8bf6cfe8-4929-40f4-ae74-46b40ef4de57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@ZayedShahcode level will be assigned to you according to the work
