### ISSUE TITLE
typo and alt for images error

### ISSUE THREAD

**Issue by betelhemdemsis** [Anushkabh/krishiconnect#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

typo error on the shop.html file 
alt for images error o index.html file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by betelhemdemsis** [comment]
I've solved the issue and made a pull request

**Comment by himanshu-03** [comment]
Fixed in #406

**Comment by betelhemdemsis** [comment]
@himanshu-03 yeah i made that pr and it's merged
