### ISSUE TITLE
Feat:Effects should be added to social media icons

### ISSUE THREAD

**Issue by PrachiJadhav2310** [Anushkabh/krishiconnect#407]
### Describe the feature

on hovering ,some effects should be added to social media icons .

### Add ScreenShots

![Uploading issue.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
> I'M NOT ABLE TO PUSH MY CODE .ACCESS IS DENIED TO ME

You will have to fork the repo and then raise a pull request from your branch to our branch's main repo.
