### ISSUE TITLE
Feat:Want Redesign footer 

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#408]
### Describe the feature

Currently footer in not looking good I could redesign it and make it better

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/29a648f2-beed-45d0-9b11-4b6a09ee5612)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
