### ISSUE TITLE
Feat: hover effect on social links in footer section

### ISSUE THREAD

**Issue by Damini2004** [Anushkabh/krishiconnect#409]
### Describe the feature

The hover effect on social links in the footer section would involve implementing a visual change that occurs when a user moves their cursor over one of the social media icons or links. This feature aims to enhance the user experience by making the footer section more interactive and visually appealing. 

### Add ScreenShots
![Screenshot 2024-06-01 025841](https://github.com/Anushkabh/krishiconnect/assets/119414762/22cbc86f-bf33-4575-b0c5-c3e825503e23)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
