### ISSUE TITLE
Adding Icons in the navbar

### ISSUE THREAD

**Issue by harshmishra19** [Anushkabh/krishiconnect#41]
-  I've noticed there are no icons in your navbar, and I believe I can enhance its visual appeal by adding icons that align with your website's theme. 
- Could you plz assign me this issue under GSSOC'24
![Screenshot 2024-05-11 080754](https://github.com/Anushkabh/krishiconnect/assets/115486960/9c0cd265-e82e-442e-969c-e7fa1a415d31)

**Comment by Syed0206** [comment]
I would like to work on this issue @Anushkabh please assign me this issue under GSSOC'24

**Comment by hritika2409** [comment]
I would like to work on this .please assign me this task

**Comment by Akshatakapare** [comment]
I would like to add some attractive icons with an animation to make them more attractive. Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!
