### ISSUE TITLE
Feat: Enhance Footer 

### ISSUE THREAD

**Issue by yashi-15** [Anushkabh/krishiconnect#412]
### Describe the feature

I aim to enhance the footer's appearance. 

- Right now, each page has a distinct footer style, which is not visually appealing. I aim to standardize the footer styling across all pages.
- Currently, the text is not clearly visible against the colorful background. My goal is to create a background that is both beautiful and subtle, complementing the website's overall theme.
- Additionally, I plan to improve the social icons' design and provide engaging yet understated hover effects. 
- Furthermore, I will apply appropriate and subtle hover effects to the footer links.

### Add ScreenShots

![Screenshot (529)](https://github.com/Anushkabh/krishiconnect/assets/132138302/03fc0113-d334-43d0-9b24-615538115445)

I want to work on this under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
