### ISSUE TITLE
BUG: Login/signup button does nothing.

### ISSUE THREAD

**Issue by yashi-15** [Anushkabh/krishiconnect#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicked on "login" or "signup" button a modal should appear where users can enter their credentials to log in or sign up. Currently, this functionality does not exist. I would like to implement this feature.

![Screenshot (532)](https://github.com/Anushkabh/krishiconnect/assets/132138302/9c4e51dd-03ae-4d5a-bc47-4dfbfc03f80d)

I want to work on this under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
level will be assigned to you according to the work
