### ISSUE TITLE
Feat: Styling the contact form

### ISSUE THREAD

**Issue by ayush-848** [Anushkabh/krishiconnect#423]
### Describe the feature

I want to create a contact form which will work when the Contact in navbar is clicked

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/126975547/8a7d4126-13ed-43bf-ad55-5ee651a2a69f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@Anushkabh Please assign this issue to me under GSSoC,24

**Comment by RitiChandak** [comment]
@ayush-848 It has already implemented
![image](https://github.com/Anushkabh/krishiconnect/assets/96969496/260754d0-390b-4111-872c-5a7f738ce04a)
are you going to improvise it if yes then how?

**Comment by ayush-848** [comment]
@RitiChandak @Anushkabh please assign this  issue to me

**Comment by ayush-848** [comment]
> @ayush-848 It has already implemented ![image](https://private-user-images.githubusercontent.com/96969496/336139424-260754d0-390b-4111-872c-5a7f738ce04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjM0MzYsIm5iZiI6MTcxNzg2MzEzNiwicGF0aCI6Ii85Njk2OTQ5Ni8zMzYxMzk0MjQtMjYwNzU0ZDAtMzkwYi00MTExLTg3MmMtNWE3ZjczOGNlMDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE2MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYTFiMDZlYmMwNjNjODNkNTU3ZDE3NTVmZjM3MzhkOWI5NmQyNWQ0ZDBhMzM2ZTM2YTg0MTFkMzhjNTc0NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.28necjEGxN0NmTcVjmZpB2frYbCrBOhfpQAo4Ye0fOg) are you going to improvise it if yes then how?

@RitiChandak 
I want to improve it
I will add few more blocks and will pad and style them properly
I will also add a space for phone number

**Comment by ayush-848** [comment]
@RitiChandak Please assign this issue to me
