### ISSUE TITLE
Deleting google option

### ISSUE THREAD

**Issue by kanishk-2** [Anushkabh/krishiconnect#424]
### Describe the feature

Deleting google option from socials because google option is usually not added on websites.

### Add ScreenShots

<img width="353" alt="socials" src="https://github.com/Anushkabh/krishiconnect/assets/157130879/71b90b54-f69b-4da9-83bf-50f07261b7b5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@kanishk-2 No need
