### ISSUE TITLE
BUG: Improve NavBar Layout

### ISSUE THREAD

**Issue by KomalSrivastava** [Anushkabh/krishiconnect#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 
Feature: Improve NavBar Layout

Objective: Enhance the navbar by adjusting its size and repositioning the logo and icons for better aesthetics and usability.

1. Adjust NavBar Size: Modify the height and padding for better proportion.
2. Reposition Logo and Icons:
    *Logo: Shift the logo towards the left.
    *Icons: Move other icons (e.g., navigation links, user profile, etc.) towards the right.

Benefits
1. Improved Layout: Creates a balanced and visually appealing navbar.
2. User Experience: Enhances navigation by making the logo and icons easily accessible.

 ScreenSchot:
![nave](https://github.com/Anushkabh/krishiconnect/assets/132221203/2e9b7d80-7cb2-4bc2-a26a-092c74e14c90)

Please assign me this issue  and add label of gssoc . i will work on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
