### ISSUE TITLE
Feat:Style to Scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [Anushkabh/krishiconnect#427]
### Describe the feature

In this webpage scrollbar is not styled it is default i will make it stylish.
it is for For better user experience
It will improve UI of the website.

One Humble request please add **level2** to this task that motivate me for my hard work and give responsibility to finish as soon as possible.

### Add ScreenShots

I will improve this style.
![image](https://github.com/Anushkabh/krishiconnect/assets/126322584/71ec8d22-62a3-4f7f-a9f5-5b277edc908b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@zalabhavy level will decide by your work and it is possible if @Anushkabh she can reject it as it is her project so you decide want to work or not

**Comment by zalabhavy** [comment]
@RitiChandak Yes , I want to Work assign and also check out my new issue no #489

**Comment by spacedust26** [comment]
Hey @Anushkabh could you please assign this issue to me? I'd like to style the scrollbar pertaining to the theme of the website.
