### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refeshing a page

### ISSUE THREAD

**Issue by aslams2020** [Anushkabh/krishiconnect#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh,

The Dark mode function gets turned off on refreshing a page or if we try to navigate to other pages through Footer. (You may check that)

I think it is due to the theme state is not being persisted when the page is refreshed. 

# What are the benefits of this modification:
I believe by storing the theme state in the browser's local storage, we ensure that:
- The theme persists across page reloads and navigations
- Even when the user navigates away from the page, the theme persist
- This provides a seamless experience for users who prefer a specific theme setting. (for example, social media and our IDEs stay on the theme mode that we have selected).

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
level will be assigned to you according to the work

**Comment by aslams2020** [comment]
hey @Anushkabh , @RitiChandak 
could you please review the solved issue with required level label.
