### ISSUE TITLE
Feat: Add "Terms and Conditions" to Helpful Links in Footer

### ISSUE THREAD

**Issue by aslams2020** [Anushkabh/krishiconnect#429]
### Describe the feature

Hey @Anushkabh,

The footer section of the website currently contains a list of helpful links. However, it is missing a crucial link to the "Terms and Conditions" page.

# Why this is needed:

- Legal Requirement: Including "Terms and Conditions" is often a legal requirement to protect both the website and its users by outlining the rules and guidelines for using the site.
- User Trust: Providing easy access to the "Terms and Conditions" helps in building trust with the users by being transparent about the website's policies.
- It is a standard practice for most websites to have a link to their "Terms and Conditions" in the footer, along with other essential links like Privacy Policy, Contact Us, etc.

I would like to contribute to this project by adding the "Terms and Conditions" link to the helpful links section in the footer.
Could you Please assign this issue under GSSOC to me so I can make the necessary changes?

### Add ScreenShots

Current footer section : 

![image](https://github.com/Anushkabh/krishiconnect/assets/131389695/c62cbf8c-021d-428a-a402-bd4c91b04007)

Proposed Footer Section with "Terms and Conditions": : 

![image](https://github.com/Anushkabh/krishiconnect/assets/131389695/c2044c10-57dc-4b39-b57a-303877fa9aa6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Anushkabh please decide
