### ISSUE TITLE
BUG: content on footer not visible properly

### ISSUE THREAD

**Issue by gyanshankar1708** [Anushkabh/krishiconnect#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/155980409/c7490da8-6bc0-47b5-8115-e7581e52f732)
The content written on the fooretr is not visible properly.
i want to work on this issue. Please assign me under GSSOC contribution.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
