### ISSUE TITLE
BUG: Tomato picture not added

### ISSUE THREAD

**Issue by gyanshankar1708** [Anushkabh/krishiconnect#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/155980409/50a13c7e-2e5a-4988-974a-3c9af255966f)
The picture of tomato is not added and the alternate text of tomato is wrong.
I want to work on this issue . Please assign me under GSSOC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
