### ISSUE TITLE
BUG: Overlapping contents on smaller devices like phones

### ISSUE THREAD

**Issue by woodwolfswee** [Anushkabh/krishiconnect#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The website is having a lot of content either hidden or overlapped in smaller devices. As most of the farmers are going to access this site using their phones, so it is important that It should be properly responsive on smaller screens also.

I would like to work on this issue to help fix this problems. I have worked on such projects before and know how to properly do it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KavyaBS123** [comment]
Hey @Anushkabh can you please assign this issue to me I would be glad to work on it!

**Comment by RitiChandak** [comment]
@woodwolfswee What's the update?

**Comment by woodwolfswee** [comment]
> @woodwolfswee What's the update?

I have already fixed the issue and sent a pull request.

https://github.com/Anushkabh/krishiconnect/pull/496

**Comment by RitiChandak** [comment]
@woodwolfswee okay

**Comment by himanshu-03** [comment]
Fixed in #496
