### ISSUE TITLE
Feat: Design beautifully MISCELLANEOUS page

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#434]
### Describe the feature

@Anushkabh 

we can design MISCELLANEOUS page when user click on MISCELLANEOUS option they will redirectd to `/miscellaneous` route

### Add ScreenShots

from this 

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/e4018147-3c62-427a-abb1-7015d19aec05)

to something like this

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/1f9ef9df-b0dc-46ff-acbd-5f85eaebe921)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
@Anushkabh 
@RitiChandak 

please assign me i would like to work on this issue

**Comment by RitiChandak** [comment]
@dhruv8433 level will be assigned after seeing your work

**Comment by dhruv8433** [comment]
@RitiChandak 

Thank you
