### ISSUE TITLE
BUG: Update CART Ui

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 

check this out,
 cart ui is not looking good

we can design it somethign like this,
![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/a61cb757-322d-49ab-9253-510bf3f018c8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Anushkabh please take a look
