### ISSUE TITLE
BUG: Cart Form is not responsive

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 

check this out,
![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/97abac9b-75e0-4028-bdc8-a9d18a5271c4)

the form is not responive and overlap in responsive devices

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@dhruv8433 This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
