### ISSUE TITLE
BUG: Burger Menu is not working

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 

check this out,

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/578b6241-21a2-4b71-8a16-0a58b29e215e)

when i  clikc on burger menu
nothing happen

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
@RitiChandak 

Thank you :)

**Comment by KavyaBS123** [comment]
Hey @Anushkabh I am GSSOC contributor can you please assign this issue to me I would be glad to work on it!

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!
