### ISSUE TITLE
BUG: Update Footer Text

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 

check this out,

the link text in footer is not proper visible

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/480000cc-f335-4028-86fb-adda652aa383)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
