### ISSUE TITLE
Background image looking compressed 

### ISSUE THREAD

**Issue by Madhu-mac** [Anushkabh/krishiconnect#44]
The background image of the shopping page looks compressed, we can add styles to it to make it consistent with the website

![Screenshot_20240511_152758](https://github.com/Anushkabh/krishiconnect/assets/99901964/00fee17c-7c6b-435b-8e1b-c02e1391a1b1)

**Comment by Madhu-mac** [comment]
@Anushkabh  Assign this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by dhanushsurendra** [comment]
@Anushkabh the background image is distorted, I can make it look better. Can you assign this to me under GSSoc'24?

**Comment by Akshatakapare** [comment]
I want to add an animated background to make it look attractive, Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by Madhu-mac** [comment]
@Anushkabh As you have replaced the shopping page image, I've made some changes for transactions and shopping cart too. Let me know if youb want any specific changes init
