### ISSUE TITLE
Feat: Contact Us Page is Missing

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#440]
### Describe the feature

@Anushkabh 

check this our, we can design `/contact` route for contact with us

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/371d9889-de65-4314-a49e-2232c8ffa042)

we can redesign somethig like this
![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/6d0884f2-617b-4435-9c63-4eb5f48b8b00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@dhruv8433 it has been fixed Please find new bug or feature
