### ISSUE TITLE
BUG:  Text in front of the image is not clearly visible

### ISSUE THREAD

**Issue by Devaki01** [Anushkabh/krishiconnect#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="788" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/147143243/268c0c40-38d5-48e5-a63a-95ab925760c8">

The text "Save time and leave the groceries to us." is not clearly visible due to background image. Can I fix this issue by either masking or changing the opacity of the background image.

<img width="953" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/147143243/6d9f60a1-45d0-4efa-bcb3-7405351c2ed2">

Also, the image of the tomato is not visible.

Can I please contribute by fixing these two issues. Please assign me this issue under ggsoc'24.
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
![image](https://github.com/Anushkabh/krishiconnect/assets/96969496/2d8b88c6-5025-475b-b531-52e3a1a209f1)
its fixed please find another bug or feature Thank You!
