### ISSUE TITLE
BUG: Text in footer of shop page not visible.

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In shop page the text is not visible properly.
![Screenshot 2024-06-02 220953](https://github.com/Anushkabh/krishiconnect/assets/169278740/c4d4a221-548b-444b-b71f-2d3a29fe0c19)

@Anushkabh  please assign this issue to me under GSSOC 2024 and add appropriate labels to it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SalehaTabassum Assigned!

**Comment by SalehaTabassum** [comment]
@RitiChandak could you please add labels

**Comment by SalehaTabassum** [comment]
@RitiChandak @Anushkabh  I have made changes in shop page footer and i found that text in footers of all pages is not properly visible.
before-
![Screenshot 2024-06-03 131049](https://github.com/Anushkabh/krishiconnect/assets/169278740/0602c1b8-6803-4951-8923-8ca8935d3e6e)

I made these changes-
![Screenshot 2024-06-03 131115](https://github.com/Anushkabh/krishiconnect/assets/169278740/9047f3cc-9b7f-4714-80bb-e8d580afca5c)

I want to make same changes to all  pages so,if you agree i will proceed

**Comment by RitiChandak** [comment]
@SalehaTabassum go for it
