### ISSUE TITLE
BUG: Conflict code lines in website

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-02 230853](https://github.com/Anushkabh/krishiconnect/assets/169278740/b1c56261-4b88-4a45-a89f-39cf7a957613)
Conflict code lines are in the website i would like to remove them.
@Anushkabh Please assign this issue to me under GSSOC 2024 and add necessary labels to it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SalehaTabassum Assigned!

**Comment by himanshu-03** [comment]
Fixed in #458
