### ISSUE TITLE
BUG:Replace Twitter icon with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [Anushkabh/krishiconnect#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/140897461/f43a2885-ebfb-40f6-b943-3f56264e72fb)
Replace Twitter icon with X in footer

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by codercake** [comment]
Hello! @RitiChandak Can you assign me this specific issue?

**Comment by himanshu-03** [comment]
Hey @AkhilaSunesh !

We have change our footer design and now we dontt need a twitter or hover.
Keep looking for more issues in the repo.

Happy Coding ✨
