### ISSUE TITLE
BUG:Update the whole footer 

### ISSUE THREAD

**Issue by Vibhu315** [Anushkabh/krishiconnect#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/93249125/0556e9f2-f914-4016-a68b-73d1eb4cfb93)
As we can see the footer text colour is barely visible,text is not aligned properly , the social media icons can be of same colour (in contrast with the page colour ).

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Vibhu315 This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
