### ISSUE TITLE
Chnages to be made in Footer page 

### ISSUE THREAD

**Issue by mehrun171** [Anushkabh/krishiconnect#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Footer Page when we hover on the links for vegetables, pulses or etc., they need to change the color of text so that user can understand that he will be clicking that link and this will improvise the usability of the Website.
-> When we hover on links,, text need to change color

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
