### ISSUE TITLE
Feature : Improvement in the My Cart page.

### ISSUE THREAD

**Issue by agrwal697** [Anushkabh/krishiconnect#462]
### Describe the feature

I think if the My Cart image section had an input-type placeholder and border-bottom in every text item so it would have better UI and also it is not aligned properly.I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC.

### Add ScreenShots

before:

![image](https://github.com/Anushkabh/krishiconnect/assets/128716726/5f331e13-28ad-4fda-b649-e519acac0d28)

after:

![image](https://github.com/Anushkabh/krishiconnect/assets/128716726/74c0496a-e56b-4d21-b421-ccd51ec1977f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@agrwal697 This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
