### ISSUE TITLE
BUG: wishlist page buttons get overlap on hover

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello PA,
In wishlist page the buttons  overlap on hovering.

https://github.com/Anushkabh/krishiconnect/assets/169278740/c1d43c23-ab99-42ec-8997-68913b046847

@Anushkabh please assign this issue under GSSOC 2024 and add appropriate labels to it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suruchibharti** [comment]
hii @Anushkabh , I want to work on this issue , please assign me.

**Comment by himanshu-03** [comment]
Fixed in #503
