### ISSUE TITLE
Feat:Improve footer section.

### ISSUE THREAD

**Issue by soniya-malviy** [Anushkabh/krishiconnect#468]
### Describe the feature

Improving footer section add good background image so the text is visible properly.

### Add ScreenShots

![Image 03-06-24 at 4 46 PM](https://github.com/Anushkabh/krishiconnect/assets/151515611/57df4ca8-8ddf-44b6-82b8-5e65936f6908)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
