### ISSUE TITLE
Fix Footer Text Visibility Issue

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Anushkabh/krishiconnect#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh 

The text in the footer of our website is currently difficult to read because it is displayed in white, blending into the background. 

Currently, the text is as follows:
![Screenshot 2024-06-03 210513](https://github.com/Anushkabh/krishiconnect/assets/159511364/4f7f2288-4705-4e62-b6f1-a0133f84aac0)

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
