### ISSUE TITLE
Redesign and Improve Visibility of 'My Cart' Section in 'My Cart' Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Anushkabh/krishiconnect#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh 

The 'My Cart' section on our website is currently not properly visible and does not have an appealing design. 

The page looks like before making the changes are as follows:
![Screenshot 2024-06-03 212142](https://github.com/Anushkabh/krishiconnect/assets/159511364/f6f2b16a-7b56-474a-be96-29db6d89b521)

**please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SaiTejaswaniBikkasani This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
