### ISSUE TITLE
BUG: Image is not showing in Tomato card

### ISSUE THREAD

**Issue by Amitanand0123** [Anushkabh/krishiconnect#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The image is not available in Tomato card which makes it look bad for user experience.
![image](https://github.com/Anushkabh/krishiconnect/assets/140126906/f0db258e-c732-48d0-b1dc-8c211ef1e636)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amitanand0123** [comment]
@Anushkabh Please assign me this issue. I will work on this.

**Comment by RitiChandak** [comment]
@Amitanand0123 This issue is already assigned
