### ISSUE TITLE
Feat:Want to Make Enter Your Details Responsive

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#491]
### Describe the feature

Currently Enter your Details page is not responsive i Want to make It responsve

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/cc14c799-8f9c-4c6d-b27d-fa863408be84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Anushkabh please look in to it

**Comment by nishant0708** [comment]
hey @RitiChandak @Anushkabh can i work on it??
