### ISSUE TITLE
Feat: Add Beautifully Design Herbs Page

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#495]
### Describe the feature

@Anushkabh 
@RitiChandak 

we can add seperate route for `/herbs` page
when user click `Herbs` option they will redirected to here

### Add ScreenShots

it will look like,
![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/f338bb04-5fbb-4be5-aab6-fa08f9e7fadf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Anushkabh please look in to it
