### ISSUE TITLE
BUG: Few Navbar icons are unnecessary placed here.

### ISSUE THREAD

**Issue by Nih1tGupta** [Anushkabh/krishiconnect#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/Anushkabh/krishiconnect/assets/119615342/99deb2c2-4308-45be-ac80-a060343b6b6f
Overlapping each other and re-appear once scrolled up

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!
