### ISSUE TITLE
working defect at social media icon

### ISSUE THREAD

**Issue by vignesh-0512** [Anushkabh/krishiconnect#50]
Hello @Anushkabh  sir, I am a gssoc'24 contributor when i looking at your site which is deployed at github in the following link https://anushkabh.github.io/krishiconnect/ i have found an issue when i click on social media icons it is not getting redirected to proper site, So i request you to assign me this issue also please provide your social media link for instagram, facebook and youtube to fix the redirecting issue.

**Comment by Anushkabh** [comment]
for now include links of insta etc .

**Comment by vignesh-0512** [comment]
can i get links of social media which i need to add into website

**Comment by vignesh-0512** [comment]
Hello @Anushkabh thanks for merging my pr into main branch i need a help when i commiting the code i have commited from another github account so in contributor list another profile has been mentioned but in gssoc i have given another profile so is it possible to change the contributor profile from vignesh-005 to vignesh-0512.
