### ISSUE TITLE
BUG: Correcting the alignment of shop page

### ISSUE THREAD

**Issue by Bhavishya2601** [Anushkabh/krishiconnect#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The images on the shop page has very large size, i want to correct it

Please assign this issue to me under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Bhavishya2601 please attach screenshot

**Comment by Bhavishya2601** [comment]
https://github.com/Anushkabh/krishiconnect/assets/147748752/b7416abb-9d0a-4510-8982-e3f3196d69a4

you can see the scrollbar also, as it is so long
