### ISSUE TITLE
Feat: Adding forgot password in login page

### ISSUE THREAD

**Issue by SalehaTabassum** [Anushkabh/krishiconnect#502]
### Describe the feature

HELLO PA,
I would like to add forgot password option in login page.

### Add ScreenShots

![Screenshot 2024-06-04 223158](https://github.com/Anushkabh/krishiconnect/assets/169278740/9f9b6f4f-b9f8-4a52-a96d-b7d743250d88)

@Anushkabh please assign this issue to me under GSSOC 2024 and add appropriate labels to it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!
