### ISSUE TITLE
DOC: Wanted to add contributors section in Readme.md file

### ISSUE THREAD

**Issue by mukund-gpt** [Anushkabh/krishiconnect#511]
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-Gopinath** [comment]
Can you please assign me this issue under Gssoc'24 @Anushkabh

**Comment by himanshu-03** [comment]
Fixed by #617
