### ISSUE TITLE
BUG: text is chaos

### ISSUE THREAD

**Issue by chaanakyaaM** [Anushkabh/krishiconnect#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/131477601/11004461-8975-4aa1-8cf2-5ec6ea1ecbe9)

When hovered the text is not correctly placed, i would like to fix this bug.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
it is already assigned
