### ISSUE TITLE
BUG: Error in contact us page

### ISSUE THREAD

**Issue by Bhavishya2601** [Anushkabh/krishiconnect#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is some error in the contact us page, it is not able to load, i want to correct it
![Screenshot 2024-06-06 204909](https://github.com/Anushkabh/krishiconnect/assets/147748752/ac6729b2-7ed2-4e44-bdc9-09cae59aa97a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-Gopinath** [comment]
Can you please assign this issue under Gssoc'24 @Anushkabh
