### ISSUE TITLE
No Nav Bar in Farmer login page and UI of the navbar is not appealing

### ISSUE THREAD

**Issue by srivastav2006** [Anushkabh/krishiconnect#52]
I want to make following changes 
1. Want to design new logo and add home button to navbar
![image](https://github.com/Anushkabh/krishiconnect/assets/143505484/52a195dc-61cb-4b8d-a9b6-2a64acdeeb46)

2. Adding nav bar to Farmer login Page to redirect to other pages easily
![image](https://github.com/Anushkabh/krishiconnect/assets/143505484/d7c4886f-d8b2-471d-adf7-aa75c5510251)

Could you please assign this issue to me under gssoc'24 so I can work on this issue.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.
