### ISSUE TITLE
BUG: Shop page not rendering properly

### ISSUE THREAD

**Issue by paulkrishanu4** [Anushkabh/krishiconnect#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/Anushkabh/krishiconnect/assets/169196836/666c1e2c-0ee5-42e5-8c89-0d0a9565cbf0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@paulkrishanu4 Any update

**Comment by paulkrishanu4** [comment]
@RitiChandak working on it looks like entire css page of shop is deleted
