### ISSUE TITLE
Redesign the UI of contact us page and make it responsive

### ISSUE THREAD

**Issue by paulkrishanu4** [Anushkabh/krishiconnect#530]
### Describe the feature

want to redesign the contact us page and make it responsive for all devices

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/169196836/9ad60392-4bba-4483-8f5f-756d7a663237

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Already assigned
