### ISSUE TITLE
BUG: change the UI of navbar

### ISSUE THREAD

**Issue by paulkrishanu4** [Anushkabh/krishiconnect#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

want to fix navbar because the colour of options are not changing on render of new page like this

https://github.com/Anushkabh/krishiconnect/assets/169196836/415d97fa-54ef-411e-81cb-d31ec61c0a22

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!
