### ISSUE TITLE
Feat:Improve UI of Footer

### ISSUE THREAD

**Issue by paridhi1509** [Anushkabh/krishiconnect#532]
### Describe the feature

The footer looks a bit faded and doesn't grab the attention of the user.
I would like to work on making it appealing and add hover effects etc to it. 

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/146311385/463af55b-5a9a-49f4-9538-3022d804f02c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@paridhi1509 Assigned

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Happy coding!

**Comment by paridhi1509** [comment]
Hi @himanshu-03 
I am currently working on improving it but i would appreciate some suggestions on it.
