### ISSUE TITLE
Feat: The twitter sign can be replaced by X.

### ISSUE THREAD

**Issue by Amishachoudhary22** [Anushkabh/krishiconnect#535]
### Describe the feature

I noticed that the Twitter icon can now be replaced with the X logo to reflect the platform's rebranding. Updating this would help keep the site current and aligned with the latest branding.

Could you please assign this issue to me? I would be happy to help make this change.

### Add ScreenShots

<img width="465" alt="Screenshot 2024-06-08 at 10 00 42 AM" src="https://github.com/Anushkabh/krishiconnect/assets/103454929/c6409840-4f96-45ea-bc6e-2642bb121e1f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Amishachoudhary22 This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
