### ISSUE TITLE
DOC: SELLER PAGE IS NOT IN PROPER FORMAT!!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [Anushkabh/krishiconnect#538]
### What's wrong with the existing documentation

The Seller page is not in the proper format... I want to align it in the proper way..

### Add ScreenShots

![Screenshot 2024-06-08 113206](https://github.com/Anushkabh/krishiconnect/assets/140592148/d81cc2f9-83e1-4dd7-9b62-5a6ffff6a57f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
please \assign me

**Comment by Aditi-Gopinath** [comment]
Can you please assign me this issue under Gssoc'24 @Anushkabh

**Comment by RitiChandak** [comment]
@SrijaVuppala295 also make the footer similar to others pages

**Comment by SrijaVuppala295** [comment]
> @SrijaVuppala295 also make the footer similar to others pages

Okay @RitiChandak
