### ISSUE TITLE
Add a login/signup page for buyers as well

### ISSUE THREAD

**Issue by samarsajad** [Anushkabh/krishiconnect#547]
### Describe the feature

adding a login/signup page is important as that way they can keep a track of their transactions and orders and access their wishlist and cart and put it in the nav bar for easy access

### Add ScreenShots

Design a signup/sign in page  something of this sort
![image](https://github.com/Anushkabh/krishiconnect/assets/142666229/8911c82b-948d-45f2-b14a-54118bfc74ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
please assign this to me @Anushkabh

**Comment by Anushkabh** [comment]
make it the first page

**Comment by samarsajad** [comment]
Okay  thanks. I will try to do it asap @Anushkabh

**Comment by himanshu-03** [comment]
@samarsajad are you still interested in doing this? If not this issue will be closed in 2 days.
