### ISSUE TITLE
BUG: Images of Shop page is too large

### ISSUE THREAD

**Issue by Husan7** [Anushkabh/krishiconnect#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to work on this issue .

![Screenshot 2024-06-09 170407](https://github.com/Anushkabh/krishiconnect/assets/162671639/a4a809ba-fdf2-49cd-95f9-ef5bc46a1721)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists
