### ISSUE TITLE
Feat:Want to implement Backend of Contact page 

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#555]
### Describe the feature

want to add backend of contact page where user can recieve email and Acknowledgement mail

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/ab38ff16-659a-49be-86bf-eb0b3c23db37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
which tech stack?

**Comment by nishant0708** [comment]
Hey @Anushkabh I can make it using js or firebase whichever you want me to use
