### ISSUE TITLE
BUG: Products section is not responsive

### ISSUE THREAD

**Issue by K-kiran77** [Anushkabh/krishiconnect#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On small screens the products section is not responsive making it looking bad.I can make the products section responsive according to different screen sizes

![Uploading Screenshot_2024-06-11-06-39-31-71_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kashi-verma** [comment]
Please assign me this isssue @Anushkabh .
