### ISSUE TITLE
Feat: PRODUCT DETAIL PAGE

### ISSUE THREAD

**Issue by Hardikchandra** [Anushkabh/krishiconnect#56]
### Describe the feature

WHEN ANY ONE CLICKS ON THE PRODUCT IT WILL REDIRECT TO THE DETAIL PAGE WHICH CONTAINS THE PRICE, IMAGE, DESCRIPTION, REVIEW SECTION, AND FURTHER DETAILS. 

### Add ScreenShots

CURRENTLY IT IS NOT PRESENT

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Hardikchandra** [comment]
WANT TO WORK ON THIS PART OF THE PROJECT.

**Comment by Hardikchandra** [comment]
@Anushkabh WANT TO WORK ON THIS PART OF THE PROJECT

**Comment by himanshu-03** [comment]
Fixed in #231
