### ISSUE TITLE
Feat: Adding a FAQ section.

### ISSUE THREAD

**Issue by nagalakshmi08** [Anushkabh/krishiconnect#561]
### Describe the feature

The Frequently Asked Questions(FAQs) section consists of the questions which commonly arise in many of the users about the website along with answers to them. This helps users to solve their doubts easily without searching more. Also this is helpful to website admins because their time is not wasted to answer to the same questions multiple times. 
I would like to add this feature to this website.

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/121669832/d0823efa-8cab-457a-ab64-5c99cbea10e8

This is my previous work on FAQ section of a website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
It already exists
