### ISSUE TITLE
BUG: Item with quantity 0 should disappear from cart

### ISSUE THREAD

**Issue by AvinashShrivastav** [Anushkabh/krishiconnect#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When an item is added to the cart, and its quantity is subsequently reduced to zero, it should be removed from the cart's item list.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AvinashShrivastav** [comment]
Hi @Anushkabh , please do also add tags to the issues. Thanks!

**Comment by himanshu-03** [comment]
Hi @AvinashShrivastav , you can start working on the issue!
