### ISSUE TITLE
BUG: Issue loading Image of Tomato below products section

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Below the Products Section where the spinach and broccoli image is loaded, the image of the tomato has not loaded and shows alt text.

I can add/upload an image of Tomato or use the existing one and fix that.

Please assign me this issue under GSSOC

<img width="1440" alt="Screenshot 2024-06-12 at 1 32 47 AM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/589323ae-33c5-4790-8bfc-32bf614c7d51">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @sahajoydeep !

Its been a long timee since we heard from you on this issue and I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
