### ISSUE TITLE
Feat: I want to add hover effect on the footer of the page in the link section

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#569]
### Describe the feature

I want to add a hover effect that aligns with the overall theme in the Products, Useful Links, and Contact Us section.

When the user hovers over them there is some hover effect, making the user realize he is hovering over those links.

Further, I suggest changing the text colour of the ' PRODUCTS '  &'  USEFUL LINKS ' & ' CONTACT ', as under them are the links to sites and pages, I want to make them a different colour and increase the font size by a bit, to catch user's attention.

Further, I suggest changing the address of  New York, NY 10012, US to an Indian address, as the entire project is based on and the theme is based out of India.

I want to solve all three problems in this issue, please assign me this issue under GSSOC.

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-06-12 at 1 37 37 AM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/f0878cc6-5e73-48b2-acd4-2d5318769272">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
add faq link to the footer

**Comment by sahajoydeep** [comment]
Where can I find the FAQ link? and shall I add this under the useful links section?

**Comment by sahajoydeep** [comment]
Should I do the hover effect on the these sections and change the address?

**Comment by sahajoydeep** [comment]
@himanshu-03 please let me know, where can I find the faq link and guide me a bit.

**Comment by sahajoydeep** [comment]
@Anushkabh please help me with the FAQ link, or if I should just add the hover effect.

**Comment by CoderGirl2844** [comment]
I would like to work on this issue 
please assign this issue to me

**Comment by sahajoydeep** [comment]
@CoderGirl2844 The issue is already assigned

**Comment by himanshu-03** [comment]
Hello @sahajoydeep !

You can find the faq.html file in our repo itself under the `src` directory.

Do let me know if you are still interested in working under this issue or not.

**Comment by CoderGirl2844** [comment]
@himanshu-03 I am interested please assign me this issue

**Comment by sahajoydeep** [comment]
@himanshu-03 got it will do it, and push it within a day

**Comment by himanshu-03** [comment]
> @himanshu-03 got it will do it, and push it within a day

You can work on the issue.
