### ISSUE TITLE
DOC:All files are scattered 

### ISSUE THREAD

**Issue by kanishk-2** [Anushkabh/krishiconnect#571]
### What's wrong with the existing documentation

All files are scattered. Will be arranging all files of html, css,js,images properly within their respective folders.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @sahajoydeep !

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
