### ISSUE TITLE
BUG: Fix Hover Effect Bug on Back-to-Top Arrow Button

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a bug with the back-to-top arrow button located at the bottom right corner of the website. When a user hovers over the button, it moves to the side, making it difficult to click.

### Steps to Reproduce
1. Scroll down to the bottom of the page.
2. Hover over the back-to-top arrow button.
3. Notice that the button shifts position when hovered over.

## Expected Behavior
The back-to-top arrow button should remain in a fixed position when hovered over and should only change its visual appearance (e.g., colour change) without moving.

## Plan to Fix
I will inspect the HTML and CSS to locate the styles affecting the button. Specifically, I will:
- Identify the CSS rules that apply to the back-to-top button and its hover state.
- Modify the CSS to ensure that the button's position remains fixed during hover.
- Test the changes locally to confirm that the button no longer moves when hovered over.

Then I'll create a pull request, please assign me this issue under GSSOC

<img width="1440" alt="Screenshot 2024-06-12 at 5 18 08 PM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/cd14c247-3a6d-435c-8e46-5e123c3ed56e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @sahajoydeep !

Its been a long time since we heard from you on this issue.
Do let me know if you are still interested in this.

Happy Coding!! ✨

**Comment by himanshu-03** [comment]
> @himanshu-03 I believe the issue is valid, when at the bottom, and trying to click on the back-to-top button, it glitches.
> 
> I wish to work on the javascript to fix the bug, requesting you to validate the issue and assign it to me.
> 
> <img alt="Screenshot 2024-07-01 at 4 40 32 PM" width="1440" src="https://private-user-images.githubusercontent.com/88198830/344652725-88e12667-1b2d-4b46-be77-05719cfc1b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzU5OTIsIm5iZiI6MTcxOTgzNTY5MiwicGF0aCI6Ii84ODE5ODgzMC8zNDQ2NTI3MjUtODhlMTI2NjctMWIyZC00YjQ2LWJlNzctMDU3MTljZmMxYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEyMDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGE4N2ZjNTMxOTEyZWUzYTZhMGQ1YzZiZmM2NGNmZTdjMGVlODVjOTFhODZmZDA3MjFiNTZjZjM0NDkyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0W29t8tg7uRdOnT1L2Khif-4Gg5Al052Lu4rpYPREMc">

Sure thing, you can work on this issue.

**Comment by sahajoydeep** [comment]
@himanshu-03 Hey Himanshu, I tried to fix the issue, but couldn't, but do let me know if you fix it or get the answer, I would love to see it.

**Comment by himanshu-03** [comment]
> @himanshu-03 Hey Himanshu, I tried to fix the issue, but couldn't, but do let me know if you fix it or get the answer, I would love to see it.

You can keep looking for the changes
