### ISSUE TITLE
Feat: Design pulses page

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#579]
### Describe the feature

@Anushkabh 
@RitiChandak 

we can design new route for  `/pulses` page

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/fb35e87f-db8b-4eb1-a0db-bcdd3199c836)

something like this

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/18c8016c-b435-4132-917f-6e78e3fe68d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
Thank you @RitiChandak

**Comment by Saloni-Kerketta** [comment]
i want to work in this project.

**Comment by himanshu-03** [comment]
Hello @dhruv8433 !

I have already mentioned about your Oil seeds PR here: #577 
Do let me know your thoughts on that first.
