### ISSUE TITLE
Feat: Adding contact us page link in home page.

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#585]
### Describe the feature

I had observed when I was clicking on the contact us page it is showing error so I want to add proper link to it.

### Add ScreenShots

![Screenshot (12)](https://github.com/Anushkabh/krishiconnect/assets/143276011/30575822-4486-439c-a53c-237af7803a41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@himanshu-03

**Comment by HarshadaGirase** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by himanshu-03** [comment]
Hello @harinisayani 

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
