### ISSUE TITLE
Feat: Adding feedback form in home page

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#586]
### Describe the feature

I want to add feedback in home page. It is better to get feedback from others to improve our website.

### Add ScreenShots

![Screenshot (12)](https://github.com/Anushkabh/krishiconnect/assets/143276011/68ccd573-2b81-40f5-aa38-271c4e9a2b6c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
@Anushkabh , @himanshu-03 I would like to work on this issue. Kindly assign me.

**Comment by himanshu-03** [comment]
Hello @harinisayani 

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
