### ISSUE TITLE
Feat: Changing favicon in home page

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#587]
### Describe the feature

I have observed favicon is not visible in home page.
I want to make it clear and visible.

### Add ScreenShots

![Screenshot (12)](https://github.com/Anushkabh/krishiconnect/assets/143276011/8f236728-c4c2-4b74-8c91-475cba897333)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harinisayani 

Its been a long timee since we heard from you on this issue.
Do let me know how you will improve or what favicon you will insert in place of this.

Happy Coding!! ✨

**Comment by harinisayani** [comment]
Hi @himanshu-03 
I want to change favicon to the webpage.
Because the favicon is not visible.
![Screenshot (184)](https://github.com/Anushkabh/krishiconnect/assets/143276011/fe003a2c-9dc7-4d27-a365-460c61de912f)

**Comment by himanshu-03** [comment]
Please let me know what is your approach will u be inserting a new favicon or changing the dimensions and properties of the current one?

**Comment by himanshu-03** [comment]
@harinisayani  are you still interested in working on this issue. If not, this issue will be closed in 2 days.

**Comment by harinisayani** [comment]
Hi @himanshu-03,
I want to insert new favicon because the current favicon is unable to visible clearly.

**Comment by himanshu-03** [comment]
> Hi @himanshu-03, I want to insert new favicon because the current favicon is unable to visible clearly. Will you please assign me this issue.

I asked you earlier which favicon are you going to use instead off this

**Comment by harinisayani** [comment]
Hi @himanshu-03,
I want to add this logo as favicon.
![Screenshot (185)](https://github.com/Anushkabh/krishiconnect/assets/143276011/b68c8ba6-db99-4eef-a1d7-fe9a2c523932)

**Comment by himanshu-03** [comment]
Sure thing, you can work on this issue.
