### ISSUE TITLE
Feat: Adding jump to top arrow in wishlist

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#588]
### Describe the feature

I had observed their is no jump to top arrow in wishlist.I want to add jump to top arrow in wishlist.

### Add ScreenShots

![Screenshot (13)](https://github.com/Anushkabh/krishiconnect/assets/143276011/85463560-8c6f-46aa-9a67-431c62d41d39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harinisayani !

You can start working on this issue. Also, it seems that we cant go to wishlist form the homepage's navbar. Can you please look at the link and change it accordingly too?

Happy Coding! ✨

**Comment by himanshu-03** [comment]
Same issue is mentioned in #591
