### ISSUE TITLE
Feat: Input fields are not working in My cart 

### ISSUE THREAD

**Issue by harinisayani** [Anushkabh/krishiconnect#589]
### Describe the feature

I had observed in My cart section input fields are not working to enter our details.
I want to make them work properly.

### Add ScreenShots

![Screenshot (14)](https://github.com/Anushkabh/krishiconnect/assets/143276011/8f3e7c62-6667-46e4-8bd5-ad21da3ac0ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harinisayani !

You can start working on this issue.
make sure all the buttons are linking to the desired  paths.

Happy Coding! ✨
