### ISSUE TITLE
DOC: Update Twitter logo with X 

### ISSUE THREAD

**Issue by Braj-01** [Anushkabh/krishiconnect#590]
### What's wrong with the existing documentation

The Twitter is now changed to X.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@himanshu-03

**Comment by himanshu-03** [comment]
hello @Braj-01 !

Someones already assigned and working on this issue. If they fail to do so, open the issue again I will assign it to you then.
Till then look for other issues in the repo (existing ones / new)

Happy Coding! ✨
