### ISSUE TITLE
Feat: adding bottom to top in mycart page

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#591]
### Describe the feature

I observed that there is no jump to top button in mycart web page.
I want to add this feature.

### Add ScreenShots

![Screenshot (177)](https://github.com/Anushkabh/krishiconnect/assets/143275265/9210dcf6-a880-460e-b05f-723c843fb6a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harikasayani !

You can start working on this issue.
Happy Coding! ✨

**Comment by himanshu-03** [comment]
@harikasayani  are you still interested in working on this issue. If not, this issue will be closed in 2 days.
