### ISSUE TITLE
Feat: Adding links to social media icons in web page

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#592]
### Describe the feature

Adding proper links to social media icons in web page.

### Add ScreenShots

![Screenshot (178)](https://github.com/Anushkabh/krishiconnect/assets/143275265/c2544ac6-2b40-4e1d-b69a-6fe8c3ab0f75)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harikasayani 

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
