### ISSUE TITLE
BUG: Changing twitter logo in webpage

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I observed that there is incorrect twitter icon in webpage.
I want to make it correct.
Please assign me this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@himanshu-03

**Comment by anshikatiwari20** [comment]
**Description:**
The current Twitter logo on the webpage is outdated and needs to be updated to the latest version of the Twitter logo. This will ensure brand consistency and enhance the visual appeal of the website. I would like to replace the existing logo with the new one and ensure it matches the styling of other social media icons.

**Screenshot:**
![Screenshot 2024-06-18 185838](https://github.com/Anushkabh/krishiconnect/assets/143124119/59d1f444-fa7c-47b0-9836-ef19262ab865)

@himanshu-03 I am a GSSoC contributor and would like to work on changing the Twitter logo on the webpage as described in issue #593. Could you please assign this issue to me ? Thank you!

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by himanshu-03** [comment]
Hello @harikasayani 

I believe this issue already been resolved.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
