### ISSUE TITLE
Feat: Enhancing wishlist page

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#594]
### Describe the feature

I want to enhance the wishlist page by adding more CSS features and fixing background-image properly.

### Add ScreenShots

![Screenshot (179)](https://github.com/Anushkabh/krishiconnect/assets/143275265/0fb32b5f-523e-4dc3-b96e-51e65fc3fc16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @harikasayani !

Please fix the issues which are assigned to you earlier.
Happy Coding ✨
