### ISSUE TITLE
BUG: Adding image according to vegetable

### ISSUE THREAD

**Issue by harikasayani** [Anushkabh/krishiconnect#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Adding correct image for vegetables in home page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harikasayani** [comment]
![Screenshot (180)](https://github.com/Anushkabh/krishiconnect/assets/143275265/e5f8df16-fecb-4575-816a-fd4b40560cc7)

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@himanshu-03

**Comment by HarshadaGirase** [comment]
@himanshu-03  I would like to work on this issue. Kindly assign me.

**Comment by himanshu-03** [comment]
Hello @harikasayani 

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
