### ISSUE TITLE
DOC: last copyright line 

### ISSUE THREAD

**Issue by kanishk-2** [Anushkabh/krishiconnect#596]
### What's wrong with the existing documentation

<img width="749" alt="krishiconnect" src="https://github.com/Anushkabh/krishiconnect/assets/157130879/9f135887-4cca-48a8-8f56-87faa1de7366">

Improving last copyright line as its not clearly visible-
The last line of website can be improved as fresh from farm and reserved is not clearly visible.
will improve this line-© 2024 Copyright: piCONNECT | Fresh from Farm. All rights reserved.
will make short precise and clearly visible text 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hello @kanishk-2 !

you can start working on this issue!
happy coding ✨
