### ISSUE TITLE
Feat: Hover effect on ChatBot Icon and also adding a ChatBot Icon 

### ISSUE THREAD

**Issue by Amruta7203** [Anushkabh/krishiconnect#599]
### Describe the feature

The ChatBot icon is missing hover effect and does not look visually appealing

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/116087736/86f56f42-774e-433e-8298-4665e2394de2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
@Amruta7203  I would like to work on this issue. Kindly assign me.

**Comment by himanshu-03** [comment]
hello @Amruta7203 !

you can start working on this issue.
Happy Coding ✨
