### ISSUE TITLE
Feat: Changing the opacity of footer image 

### ISSUE THREAD

**Issue by Amruta7203** [Anushkabh/krishiconnect#600]
### Describe the feature

The opacity of the footer image needs to be reduced so that the text and links are clearly visible to the users.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/116087736/d2ce8e21-ce4b-4fb2-b21d-e41dd8a71773)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@himanshu-03

**Comment by himanshu-03** [comment]
hey @Amruta7203 !

you can start working on this issue.
Happy Coding ✨

**Comment by himanshu-03** [comment]
Hey @Amruta7203 !

The footer has been revampled I dont think we need this feature now.
kepp looking for more issues

Happy Coding ✨
