### ISSUE TITLE
Feat: Add a scroll bar complementing the theme of the website 

### ISSUE THREAD

**Issue by Amruta7203** [Anushkabh/krishiconnect#602]
### Describe the feature

The current scroll bar makes the website less visually appealing. beautifying the scroll bar by altering its width and color can improve the user experience and better visual appeal

### Add ScreenShots

Current scroll bar:
![image](https://github.com/Anushkabh/krishiconnect/assets/116087736/bb1cfb8d-f8f8-49f2-bad6-df393785aeb0)

After adding custom scrollbar:
![image](https://github.com/Anushkabh/krishiconnect/assets/116087736/39182dc6-5a58-4286-b396-4bf7880df76d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @Amruta7203!

please fix the asssigned issues first and let me know when u are done with them first.

**Comment by himanshu-03** [comment]
Hey @Amruta7203 !

I dont think there is a need for a custom scroll bar instead we should remove it all apart from the website.
keep looking for other issues in the repo.

happy coding ✨
