### ISSUE TITLE
BUG: Hover effect on Icon not working 

### ISSUE THREAD

**Issue by DevGajjar28** [Anushkabh/krishiconnect#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At transaction page footer , hover effect is not working on icons 
![image](https://github.com/Anushkabh/krishiconnect/assets/145287513/37d56e54-0a10-461c-8311-f0f8603a6a64)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshikatiwari20** [comment]
**Description:**
The hover effect on the specified icon is currently not working. I would like to fix the issue to ensure that the hover effect is properly applied, enhancing the user interface and user experience. This fix will make the icons more interactive and visually appealing.

**Screenshot:**
![Screenshot 2024-06-18 185838](https://github.com/Anushkabh/krishiconnect/assets/143124119/77536742-c81e-46c9-9e5b-f64cef88def0)

@Anushkabh I am a GSSoC contributor and would like to work on fixing the hover effect on the icon as described in issue #606. Could you please assign this issue to me? Thank you!

**Comment by himanshu-03** [comment]
@DevGajjar28 are you a GSSoC contributor or not?
