### ISSUE TITLE
Add Toastify Message

### ISSUE THREAD

**Issue by sailaja-adapa** [Anushkabh/krishiconnect#607]
### Describe the feature

Hello My name is A.A.D.Sailaja I would like to add Toastify Message on Rate Us page to make it more Responsive and it will also increase the User Experience
As you can See in the below video
can you assign me this issue under GSSOC'24 @Anushkabh 

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/161804629/903f447f-1464-496f-85e7-7dc5994ef4de

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
@Anushkabh can you assign me this issue under GSSOC'24

**Comment by sailaja-adapa** [comment]
@himanshu-03 can you assign me this issue under GSSOC'24

**Comment by sailaja-adapa** [comment]
can you assign me this issue under GSSOC'24 @Anushkabh @himanshu-03

**Comment by HarshadaGirase** [comment]
@himanshu-03 I would like to work on this issue. Kindly assign me.

**Comment by himanshu-03** [comment]
Hello @sailaja-adapa !

You can start working on this issue.
Happy Coding ✨

**Comment by sailaja-adapa** [comment]
okkk @himanshu-03
