### ISSUE TITLE
Enhance Rate Us Page

### ISSUE THREAD

**Issue by sailaja-adapa** [Anushkabh/krishiconnect#608]
### Describe the feature

Hello Project Admin
i would like to Enhance Rate Us page to make it make more attractive by adding hover,lighting,some changes to star logic like that 

### Add ScreenShots

![kkk](https://github.com/Anushkabh/krishiconnect/assets/161804629/41c9e346-7054-417b-9c9c-5f66eb1ec7fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
@Anushkabh can you assign me this issue under GSSOC'24

**Comment by sailaja-adapa** [comment]
@himanshu-03 can you assign me this issue under GSSOC'24

**Comment by sailaja-adapa** [comment]
can you assign me this issue under GSSOC'24 @Anushkabh @himanshu-03

**Comment by himanshu-03** [comment]
Hello @sailaja-adapa !

i dont think it is necessary to do the required changes.
Look for another issues in the repo or try finding some.

happy Coding ✨

**Comment by sailaja-adapa** [comment]
@himanshu-03 OKk Thank you :)
