### ISSUE TITLE
Feat:Footer Is Not Going With Ui 

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#610]
### Describe the feature

Currently The Footer is very much bad which is affecting the asthetics of the website . I want to fix that

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/fac4a2e3-b484-4323-8ab3-064236ee045e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @nishant0708 !

I believe that the footer must be same throughout the website and it should be aesthetically pleasant. Can you do the required changes in all the pages, so  that footer becomes same throughout the website?

happy Coding ✨

**Comment by himanshu-03** [comment]
> Reference in new iss

if you do the mentioned thing I will assign it as level 3.

**Comment by nishant0708** [comment]
@himanshu-03 I will make it consistent throughout all webpages no issues just leave it to me

**Comment by himanshu-03** [comment]
Great @nishant0708

**Comment by nishant0708** [comment]
Hey @himanshu-03 can you provide me with some links you want in footer or some details you need

**Comment by himanshu-03** [comment]
> Hey @himanshu-03 can you provide me with some links you want in footer or some details you need

Fow now focus on maintaining the consistency and UI, will do that later.
