### ISSUE TITLE
Feat:want to add search bar in shop page 

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#612]
### Describe the feature

want to search bar in shop page so that user can search item what they want

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/a91128ce-ed19-4781-8c30-edd3bc002fac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by guneetdewangan9** [comment]
I would like to solve this issue. Please assign me this issue under GSSoC'24 to contribute to this project.

**Comment by himanshu-03** [comment]
Hello @nishant0708 !

please solve the issues which are assigned to your first and also if we search will we get the desired search option or not? Do highlight some points and features of the search  bar.

best of luck ✨

**Comment by nishant0708** [comment]
@himanshu-03  See when we will search it should search both category wise and product wise as well like if I searched for dals it should show be dals and show all the products with all the products with dal category so fo this I will need to update everyone card with category name as well so no worries I will finish my current assigned issues first then you can assign me this

**Comment by himanshu-03** [comment]
> @himanshu-03 See when we will search it should search both category wise and product wise as well like if I searched for dals it should show be dals and show all the products with all the products with dal category so fo this I will need to update everyone card with category name as well so no worries I will finish my current assigned issues first then you can assign me this

Okay just tag me in this issue and I will assign you once you are done with the previous ones.

**Comment by nishant0708** [comment]
Hey @himanshu-03  can I start working on this now

**Comment by himanshu-03** [comment]
Yes you can

> Hey @himanshu-03 can I start working on this now
