### ISSUE TITLE
BUG:user increase the quantity then not change the price value

### ISSUE THREAD

**Issue by Varsani2520** [Anushkabh/krishiconnect#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

user increase the quantity then not change the price value
expected:when user increase the quantity then also increase the price as well as decrease quantity then decrese the price 
![image](https://github.com/Anushkabh/krishiconnect/assets/137641079/08c40257-ffd4-4a25-abb3-16b7449ea4c5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @Varsani2520  !

I believe this issue is now already resolved on our website.
Keep looking for new issues or go through the existing issues for contributing on our repo.

Happy Coding!! ✨
