### ISSUE TITLE
Feat:Adding A subscribe button at footer

### ISSUE THREAD

**Issue by taniya542** [Anushkabh/krishiconnect#614]
### Describe the feature

Subscribe button can be added to the footer.Please assign me this issue under GSSOC 24.

### Add ScreenShots

![WhatsApp Image 2024-06-14 at 19 14 29_f52fc047](https://github.com/Anushkabh/krishiconnect/assets/143064148/6b493601-c651-4d21-a54f-b62145906d16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
> @himanshu-03, I noticed that this issue was added to the project. Could you please confirm if it's assigned to me or not?

Can you please mention the issue or PR where it  is solved?

**Comment by himanshu-03** [comment]
Are you talking about the social links button? @taniya542

**Comment by himanshu-03** [comment]
If yes, then it is already been done you can look out for another open issues in the repo.
