### ISSUE TITLE
BUG: Chatbot Window Size Too Large ,gets obscured by Navbar

### ISSUE THREAD

**Issue by Nidhi1314** [Anushkabh/krishiconnect#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of bug:

I've noticed that the chatbot window on your website is excessively large. This causes the top part of the window to be hidden behind the navbar.

Attached is screenshot showcasing the issue on a desktop. As you can see, the top portion of the chatbot window is hidden behind the navbar, making it visually unprofessional.
Ideally, the chatbot window should be resized to fit comfortably within the viewport without obstructing any other website elements.

### Screenshot: 
![image](https://github.com/Anushkabh/krishiconnect/assets/146202184/01aeb5c8-388b-47fa-a4b5-4ba580870f67)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nidhi1314** [comment]
@himanshu-03 I think its already corrected as when I open the code in my editor it shows this-
![image](https://github.com/Anushkabh/krishiconnect/assets/146202184/c31912f1-24e9-4f8e-9afd-a04cf92c5bca)

**Comment by himanshu-03** [comment]
Okay @Nidhi1314 

you can look for another open issues on the repo or find a new one!
Best of Luck ✨
