### ISSUE TITLE
Feat: Add Validation to Login and Registration Forms for Buyers

### ISSUE THREAD

**Issue by revanth1718** [Anushkabh/krishiconnect#620]
### Describe the feature

Enhance the buyer login and registration forms by implementing comprehensive validation. This will ensure data integrity and improve user experience by providing immediate feedback on input errors.

### Add ScreenShots

![Screenshot (608)](https://github.com/Anushkabh/krishiconnect/assets/109272714/ebbea33d-ab6c-4875-8779-ba758871457d)
![Screenshot (609)](https://github.com/Anushkabh/krishiconnect/assets/109272714/9b65512e-0e2c-407b-8f58-2bfbd6e3a21c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by himanshu-03** [comment]
Hello @revanth1718 !

You can start working on this issue.
Happy Coding ✨

**Comment by UtkarshBirla28** [comment]
@himanshu-03 Assign it to me sir i will reolve it ASAP
