### ISSUE TITLE
Feat: Create a Responsive Footer with Location Information

### ISSUE THREAD

**Issue by revanth1718** [Anushkabh/krishiconnect#621]
### Describe the feature

Enhance the application by designing and implementing a responsive footer that includes the company's location. This footer should be adaptable to different screen sizes and provide essential information accessibly.

### Add ScreenShots

![Screenshot (610)](https://github.com/Anushkabh/krishiconnect/assets/109272714/1b787319-d8f8-4a27-955c-2a5b747c1724)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sahajoydeep** [comment]
Similar Issue might be opened to make the footer interactive and adding location information.

**Comment by revanth1718** [comment]
assign this issue to me

**Comment by sahajoydeep** [comment]
@himanshu-03 I believe I have opened similar issue earlier.

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by RitiChandak** [comment]
the footer is already responsive

**Comment by himanshu-03** [comment]
> @himanshu-03 I believe I have opened similar issue earlier.

Yes you need not worry it is assigned to you as of now.
