### ISSUE TITLE
Feat:Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by deepak00944** [Anushkabh/krishiconnect#623]
### Describe the feature

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/119965267/0eceda54-2ce5-41dd-aafb-8f73b545d707)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hey @deepak00944 !

I dont think this is a metric we need to display publicly. We can have this stats anyways from the domains we have hosted on.
Keep looking forr more issue in the repo

Happy Coding ✨
