### ISSUE TITLE
Resource Library for Sustainable Practices

### ISSUE THREAD

**Issue by ankitgupta143** [Anushkabh/krishiconnect#628]
### Describe the feature

Build an interactive library of articles, tips, and guides on sustainable farming practices.
Implement a search and filter functionality using JavaScript.

### Add ScreenShots

![Screenshot 2024-06-18 111150](https://github.com/Anushkabh/krishiconnect/assets/114281117/31a2f5a9-fbbe-41ce-ad3b-f9971b9193ae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hry @ankitgupta143 !

Do you mean adding a blogs and articles section on the website?

**Comment by himanshu-03** [comment]
Elaborate more on your issue.

**Comment by ankitgupta143** [comment]
@himanshu-03 
Display a list of articles, tips, and guides.
Allow users to search for articles by keywords.
Provide filter options based on categories or tags.
Ensure the UI is user-friendly and interactive.

**Comment by himanshu-03** [comment]
Hey @ankitgupta143 !

We already have an issue assigned to someone for creating a blog page.
Keep lookingg for more issues in the repo anf if the assigned issue is not completely properly you can takee over after reopening the issue.

Happy Coding ✨

**Comment by ankitgupta143** [comment]
@himanshu-03 
I can add the search and filter functionality which is not present in your site. The user interface includes a search bar for keyword input and filter options like checkboxes for selecting categories or tags. When a user types in the search bar or selects filter options, these inputs are captured through event handlers. The filtering logic then processes these inputs: it checks if each article's title or content matches the search keyword and if the article's tags match any selected categories.

**Comment by himanshu-03** [comment]
> @himanshu-03 I can add the search and filter functionality which is not present in your site. The user interface includes a search bar for keyword input and filter options like checkboxes for selecting categories or tags. When a user types in the search bar or selects filter options, these inputs are captured through event handlers. The filtering logic then processes these inputs: it checks if each article's title or content matches the search keyword and if the article's tags match any selected categories.

Yes this issue is assigned to someone! If they fail to match the expectations you can continue to work on that in future.
