### ISSUE TITLE
Feat: Adding google map 

### ISSUE THREAD

**Issue by GAVINESHWAR** [Anushkabh/krishiconnect#631]
### Describe the feature

In the footer section we can add google map option to check the address through the maps which make better experience to the user.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/124431955/305a0201-1820-47e3-b335-bb6a0db16f1f)
These kind of feature i would like to add 

Assign me this issue @Anushkabh to make contribution to the project
Thank you 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
map is already added
