### ISSUE TITLE
BUG: Contact Us page not working 

### ISSUE THREAD

**Issue by CoderGirl2844** [Anushkabh/krishiconnect#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in nav bar after selecting the contact us button it throws an error page
![Screenshot 2024-06-19 011355](https://github.com/Anushkabh/krishiconnect/assets/155231566/9ac59617-89d1-4aee-9dd0-fdafaa48afbb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
It is working
