### ISSUE TITLE
Feat: Create blog page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Anushkabh/krishiconnect#635]
### Describe the feature

I would like to add a blog page for this website. It includes blog articles regarding buying guides, product categories, technology related etc. topics.

### Add ScreenShots

![Screenshot 2024-06-19 081924](https://github.com/Anushkabh/krishiconnect/assets/139672976/d458b3ba-c7d8-4ad8-8647-5f74a340fc42)
![Screenshot 2024-06-19 081956](https://github.com/Anushkabh/krishiconnect/assets/139672976/f7d06e29-d554-4031-99b7-ad56760da4d7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by himanshu-03** [comment]
Hello @DharshiBalasubramaniyam !

You can start working on this issue. Just wanted to clear out this will be a seperate section right? and do u wish to showcase a small glimpse of this on the homepage too?

**Comment by DharshiBalasubramaniyam** [comment]
> Hello @DharshiBalasubramaniyam !
> 
> You can start working on this issue. Just wanted to clear out this will be a seperate section right? and do u wish to showcase a small glimpse of this on the homepage too?
> 
> Happy Coding ✨

Hi @himanshu-03,

Thank you for assigning the issue.

I propose creating a separate page dedicated to blogs, with a link to this page added in the footer for easy access. Additionally, I can incorporate a "Latest Blogs" section on the homepage, featuring the most recent blog posts. This section would include a "View More" button, which would redirect users to the full blog page.

Please let me know if you would like me to proceed with this approach or if you have any further suggestions.

**Comment by himanshu-03** [comment]
> > Hello @DharshiBalasubramaniyam !
> > You can start working on this issue. Just wanted to clear out this will be a seperate section right? and do u wish to showcase a small glimpse of this on the homepage too?
> > Happy Coding ✨
> 
> Hi @himanshu-03,
> 
> Thank you for assigning the issue.
> 
> I propose creating a separate page dedicated to blogs, with a link to this page added in the footer for easy access. Additionally, I can incorporate a "Latest Blogs" section on the homepage, featuring the most recent blog posts. This section would include a "View More" button, which would redirect users to the full blog page.
> 
> Please let me know if you would like me to proceed with this approach or if you have any further suggestions.

Yes  that would be great!
You can start working on this issue.
