### ISSUE TITLE
BUG:Toggle theme is not working in contact us page

### ISSUE THREAD

**Issue by Rohitha-pudu** [Anushkabh/krishiconnect#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/116823590/0384fc72-8f3a-4a15-a062-8dc7c2a3ccd7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Rohitha-pudu Assigned!

**Comment by RitiChandak** [comment]
Hi @Rohitha-pudu, I sincerely apologize for the mistake. This issue is a duplicate, so I will close the issue and the PR.

**Comment by RitiChandak** [comment]
For your reference #598
