### ISSUE TITLE
Feat: New background for rate us page

### ISSUE THREAD

**Issue by arpy8** [Anushkabh/krishiconnect#643]
### Describe the feature

The current image for the background in the rate us page is quite pixelated. I would like to fix this.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/74809468/81d5cf8b-ebfc-4a0f-a685-12df82e722d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RitiChandak** [comment]
which image you are going to use?
