### ISSUE TITLE
BUG: Excessive padding in the contact section

### ISSUE THREAD

**Issue by arpy8** [Anushkabh/krishiconnect#644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Contact Us" div is taking up an excessive amount of space in the viewport. I would like to fix this

![image](https://github.com/Anushkabh/krishiconnect/assets/74809468/4d35c684-01e4-4122-8565-91b1ce6cae7f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by himanshu-03** [comment]
hey @arpy8 !

The whole contact page enhancement is already assigned to someone else.
Keep looking for more issues in the repo.

Happy Coding ✨
