### ISSUE TITLE
#making the logo similar in all the pages

### ISSUE THREAD

**Issue by nandani-goyal** [Anushkabh/krishiconnect#646]
### What's wrong with the existing documentation

the logo in the navbar is not similar in all the web pages. Please assign me this work under gssoc'24.

### Add ScreenShots

![Screenshot 2024-06-21 113142](https://github.com/Anushkabh/krishiconnect/assets/152094228/6609b8fe-618a-48bb-8fce-86004303452f)
logo on my cart page
![Screenshot 2024-06-21 113159](https://github.com/Anushkabh/krishiconnect/assets/152094228/0a76a1fa-37e3-4c76-b641-c0836083a2b1)
logo on shopping page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.
