### ISSUE TITLE
BUG: Wishlist in navigation bar should be more enhanced 

### ISSUE THREAD

**Issue by yogirajbshinde21** [Anushkabh/krishiconnect#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-21 191129](https://github.com/Anushkabh/krishiconnect/assets/84953719/573f543f-b962-472a-bbfd-6a4ecb99747f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@yogirajbshinde21 Please provide me with the details on how you are going to enhance it.

**Comment by yogirajbshinde21** [comment]
> @yogirajbshinde21 Please provide me with the details on how you are going to enhance it.

@RitiChandak I have several things to make navigation bar more better :
1. Glass effect/Transparent Effect
2. Classy Hover effects while hovering over each navigation items.
3. In Dark mode, navigation bar should also be dark instead of showing Light white color.
Let me know if you have any suggestion!

**Comment by himanshu-03** [comment]
Hello @yogirajbshinde21 !

This  issue is assigned to someone else.
happy Coding ✨
