### ISSUE TITLE
Footer in the Wishlist should be corrected

### ISSUE THREAD

**Issue by anagha-chaudhari** [Anushkabh/krishiconnect#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To maintain the uniformity of footers on all pages, the footer of wishlist page should be corrected. Right now, there is a plague white layer on the footer which should be removed. Please assign this to me under GSSOC'24

![krishiFooter](https://github.com/Anushkabh/krishiconnect/assets/143149376/08a095d6-1679-47a2-89ae-548a38c20454)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello,

Our footer is revamped and we dont think it is necessary to have his feature on our website right now.
keep looking for more issues in the repo.

Happy Coding ✨
