### ISSUE TITLE
Hover Effect on footer links are missing

### ISSUE THREAD

**Issue by SumithThota** [Anushkabh/krishiconnect#653]
### Describe the feature

Hover Effect on footer links are missing 
Let me add a better hover effect that can able to match with your projrct color scheme

## Check this:

https://github.com/Anushkabh/krishiconnect/assets/108344062/8be47d10-ecc4-4905-bec1-19884603cc98

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SumithThota, please ensure the same uniformity is maintained across the website

**Comment by himanshu-03** [comment]
Hello,

Our footer is revamped and we dont think it is necessary to have his feature on our website right now.
keep looking for more issues in the repo.

Happy Coding ✨

**Comment by SumithThota** [comment]
ok fine
