### ISSUE TITLE
Feat:Missing Hover on Social Icons In Transaction page

### ISSUE THREAD

**Issue by SumithThota** [Anushkabh/krishiconnect#654]
### Describe the feature

Missing Hover Effect on Social Icons In Transaction page
Let me fix it as a GSSCO24 conributor

### Add ScreenShots

check tis video once:
https://github.com/Anushkabh/krishiconnect/assets/108344062/4011f029-c579-4c74-8025-fee61abdc066

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@SumithThota please ensure the same uniformity is maintained across the website

**Comment by SumithThota** [comment]
@RitiChandak, Yes I will maintain the same uniformity
