### ISSUE TITLE
BUG:Lesser Font Weight to  contact us div in carts Section

### ISSUE THREAD

**Issue by SumithThota** [Anushkabh/krishiconnect#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi PA(@Anushkabh),
There was to lesser Font Weight to contact us text div in carts page 
which make user unable to see so let me make it more clear 
Assign me this issue as a GSSCOC24 contributor 

## check this Screen shot
![Screenshot 2024-06-22 124417](https://github.com/Anushkabh/krishiconnect/assets/108344062/71009006-c70c-4cac-9a9b-a3ce4361ec89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @SumithThota !
Our footer is already undergoing changes and will be updated soon.

Keep looking for more issues on the repo and website.
happy coding ✨
