### ISSUE TITLE
BUG: Misaligned Content on Website

### ISSUE THREAD

**Issue by Rupalpy** [Anushkabh/krishiconnect#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240622_221330](https://github.com/Anushkabh/krishiconnect/assets/121295967/f04ec79b-5bdc-4ed7-8ceb-4309791ffcef)
There is a misalignment issue on the website where some elements appear slightly up or down relative to each other. This affects the visual consistency and layout.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi @Rupalpy !

The footer is already been assigned and undergoing chnges, we will be updating it very soon.
Keep looking for new issues in the repo and website.

happy coding ✨
