### ISSUE TITLE
🌟 Feature: Add a Scroll Down "Progress Bar"

### ISSUE THREAD

**Issue by aslams2020** [Anushkabh/krishiconnect#658]
### Describe the feature

Hey @Anushkabh & @RitiChandak, @himanshu-03 
I want to add a **"Scroll Down Progress Bar"**

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page. The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

**Expected Outcome**
The scroll down progress bar will provide users with a better understanding of their position on the page, enhancing navigation and overall user experience.

### Add ScreenShots

Example Like this - 

![WhatsApp Image 2024-06-23 at 00 03 04_03f80295](https://github.com/Anushkabh/krishiconnect/assets/131389695/778dce80-b90f-4ef7-931e-06f1622cb6b1)

Could you please assign me this issue under GSSOC'24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@Anushkabh @RitiChandak

**Comment by himanshu-03** [comment]
Hello @aslams2020 !

I dont think that someone is interested in looking at the progress bar of the page. Our main motive is to deliver the content and experience with ease. The page can be bigger but should be insightful.

Keep looking for more issues in the repo.

happy coding ✨

**Comment by aslams2020** [comment]
> Hello @aslams2020 !
> 
> I dont think that someone is interested in looking at the progress bar of the page. Our main motive is to deliver the content and experience with ease. The page can be bigger but should be insightful.
> 
> Keep looking for more issues in the repo.
> 
> happy coding ✨

Yes, I understand..
Thankyou for responding ✌️
