### ISSUE TITLE
enhance the Rate Us page and Toastify message after hitting submit

### ISSUE THREAD

**Issue by anagha-chaudhari** [Anushkabh/krishiconnect#659]
### Describe the feature

The rate us page can be enhanced. We can add navbar and footer to it like other pages for the user to be able to navigate even from the rate us page, improve the background and add a creative toastified message after the user hits the submit button, to let them know that the feedback has been submitted. Can you assign me this issue under Gssoc'24?

### Add ScreenShots

![krishi_rateus](https://github.com/Anushkabh/krishiconnect/assets/143149376/02bc2831-a30c-46d5-b3c2-ffdde70e0b56)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @anagha-chaudhari !

You can start working on this issue.

happy coding ✨
