### ISSUE TITLE
BUG:Add Home page option to navbar

### ISSUE THREAD

**Issue by Pratik2401** [Anushkabh/krishiconnect#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The landing page is not available in navbar.Therefore whenever we leave the page we cannot return to landing page.
![image](https://github.com/Anushkabh/krishiconnect/assets/105542579/9ee36d90-ffa5-40fe-8570-fdefd80178b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratik2401** [comment]
pls assign these issue to me under GSSOC'24

**Comment by Jamir2412** [comment]
@Anushkabh Can you please assign this issue to me and add gssoc label..?
