### ISSUE TITLE
BUG:payment integration 

### ISSUE THREAD

**Issue by Varsani2520** [Anushkabh/krishiconnect#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i click on order now button then nothing to show anything

how to solved :
user click on that button then open payment page or modal for pay that 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@RitiChandak ,please assign this

**Comment by himanshu-03** [comment]
Hey @Varsani2520 !

You can start working on this issue.

happy coding ✨
