### ISSUE TITLE
Feat: Introducing authentic spices and fresh flowers in krishiconnect

### ISSUE THREAD

**Issue by Vin205** [Anushkabh/krishiconnect#662]
### Describe the feature

Apart from vegetables and fruits, Fresh flowers and  authentic spices should also be introduced as they are in great demand in market. A section for information related to spices and flowers can be introduced in website.

### Add ScreenShots

![3](https://github.com/Anushkabh/krishiconnect/assets/138381350/11d3cbca-81e2-4592-9362-e462cefdb833)
![1](https://github.com/Anushkabh/krishiconnect/assets/138381350/d8ac2339-4995-4b27-beb1-b1b57cfd92b0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hey @Vin205 !

the blogs and info sections for the products is already implemented by someone else.
Keep looking for new issues in the repo.

Happy coding ✨
