### ISSUE TITLE
BUG: Rate Us page not have message after submit details also page have no favicon.

### ISSUE THREAD

**Issue by zalabhavy** [Anushkabh/krishiconnect#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I will add message after submit form that  Thank you for your feedback ! 
also add favicon to this page.

![image](https://github.com/Anushkabh/krishiconnect/assets/126322584/7a714ca7-9f2f-4b1c-98bc-a8779a39c3f4)
![image](https://github.com/Anushkabh/krishiconnect/assets/126322584/ba04dfc2-471c-4f8a-9553-b6476b97c893)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Anushkabh Please assign me !

**Comment by himanshu-03** [comment]
Hello @zalabhavy !

The rate us page enhancement is already assigned to someone.
keep looking for more issues in the repo.

Happy Coding ✨
