### ISSUE TITLE
Feat: I want to improve the transaction footer section.

### ISSUE THREAD

**Issue by Bhumika1312** [Anushkabh/krishiconnect#664]
### Describe the feature

I would like to enhance the appearance of the transaction footer section to make it more presentable.
Thank you!

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/115869626/bdfc30b1-13be-4295-a1d6-7acc64d64dc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @Bhumika1312 !
the footer is already been enhanced by a contributor and will be merged soon.
Keep looking for more issues in the repo.

happy coding ✨
