### ISSUE TITLE
BUG:Input cannot be entered in the input fields on the my cart page.

### ISSUE THREAD

**Issue by meetarora10** [Anushkabh/krishiconnect#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We cannot enter any value in the input fields of my cart page also the order now button on the same page on click does not gives any response.
Assign this task to me and I can correct the above mentioned issues added with other styling.
![Screenshot (514)](https://github.com/Anushkabh/krishiconnect/assets/143121854/8cd4ee25-052f-4502-a413-7ab30fdf4927)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hello @meetarora10 !

This issue iss already been addressed and fixed.
Keep looking for more issues in the repo.

Happy Coding ✨
