### ISSUE TITLE
Email input in the contact form

### ISSUE THREAD

**Issue by Ajita369** [Anushkabh/krishiconnect#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Email form is accepting wrong input and is giving wrong message . The message should be to enter a valid email address and when the email is correct it should give thank you message .
Here is a screenshot : 
![image](https://github.com/Anushkabh/krishiconnect/assets/162597493/50473b91-e56f-4706-8d7a-f68bf8978060)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @Ajita369 !

You can start working on this issue.
happy coding ✨
