### ISSUE TITLE
Feat: Redesign the Logo and Favicon

### ISSUE THREAD

**Issue by sanskritisahu21** [Anushkabh/krishiconnect#669]
### Describe the feature

Current logo is not visible in the Favicon.

### Add ScreenShots

![Screenshot 2024-06-26 221900](https://github.com/Anushkabh/krishiconnect/assets/134837879/3e801e90-ad46-4997-8981-34bbcb0ea984)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanskritisahu21** [comment]
@Anushkabh Please assign me this issue under gssoc

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by himanshu-03** [comment]
Hello @sanskritisahu21 !

this issue is already assigned to someone else in the repo.
Keep looking for changes if it isnt changes in the next few days it wll  be assigned to you.

Till then keep looking for new issues in the repo.

Happy Coding ✨
