### ISSUE TITLE
Feat:Show products through json format in js rather than directly showing in html and also adding a search bar to shopping section

### ISSUE THREAD

**Issue by Pratik2401** [Anushkabh/krishiconnect#67]
### Describe the feature

The products can be shown by using js and storing data in json format and also add a search bar to shopping section for easy search.pls assign these issue to me under GSSOC'24

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/105542579/34324a3b-edb6-4b50-b7e6-cb5ec9b46f3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@Pratik2401  could you convert the current backend of firebase to node,js and mongodb?
you can create 3-4 prs , i'll allot level 3 to each.

**Comment by Pratik2401** [comment]
It do such one I will need great time to spend on it currently I am student of SE and my endsem will be till 28. I can start it from 28 May and complete it as my highest priority if it is ok
