### ISSUE TITLE
Feat: Footer: Social media transform and transition effects 

### ISSUE THREAD

**Issue by sakeel-103** [Anushkabh/krishiconnect#672]
### Describe the feature

In the footer section there is no transition effects on the social media icons. 

@Anushkabh 
Dear PA please assign this to me under gssoc'24

### Add ScreenShots

video -

https://github.com/Anushkabh/krishiconnect/assets/136844498/5b43bf63-c331-400c-ae1f-27efa85575e0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @sakeel-103 !

The footer is already undergoing changes in the assigend repo and issues.
Keep looking for more issues in the repo or website.

Happy Coding ✨
