### ISSUE TITLE
Feature💡: Add "Privacy Policy" and "Terms and Conditions" Pages to Footer 

### ISSUE THREAD

**Issue by aslams2020** [Anushkabh/krishiconnect#674]
### Describe the feature

Hey @RitiChandak and @Anushkabh 

I want to suggest a feature request to you which is essential - 

Currently, the website footer does not have a dedicated section for legal pages. To enhance user experience and ensure compliance, we need to add a new column labeled "LEGAL" in the footer. 
This column should include links to the "Terms and Conditions" and "Privacy Policy" pages.

### What will I Do ? 

1. Modify the footer layout to **include a New Column labeled "LEGAL"**. 
2. **Create a "Terms and Conditions" page** and **Add links** to it in LEGAL Column. 
3. **Create a "Privacy Policy" page** and **Add links** to it in LEGAL Column.  
(**NOTE:** I will Ensure that the new column follows the existing footer styling for consistency)

This is where i will do these tasks. It will be very beneficial to have a LEGAL pages section.
Current footer :
![image](https://github.com/Anushkabh/krishiconnect/assets/131389695/23ace866-d63f-42d5-8c4a-abecc8e368d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@RitiChandak  @himanshu-03 please assign.

**Comment by himanshu-03** [comment]
Hello @aslams2020 !

the repo is undergoing various changes wrt to footer right now.
Please fix this in the updated footer after we merge he changes.

Happy Coding ✨

**Comment by aslams2020** [comment]
Sure @himanshu-03.

**Comment by himanshu-03** [comment]
Hey @aslams2020 !

the footer is updated you still up for doing this changes?

**Comment by aslams2020** [comment]
Yes @himanshu-03 , I'll do this!

**Comment by aslams2020** [comment]
@himanshu-03 Please take a look and review it.
