### ISSUE TITLE
DOC:update scripts.js

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Anushkabh/krishiconnect#675]
### What's wrong with the existing documentation

we need to add few things to the existing code

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hello @AKSHITHA-CHILUKA !

It would be great if you acan elaborate what your changes would do in your PR

**Comment by AKSHITHA-CHILUKA** [comment]
Added more error handling for the API calls and removed duplicate email variable declarations also added a reset to the users array in getAllData to avoid duplications and updated the table to ensure that multiple rows are not added incorrectly and 
moved some of the inline style updates to document.getElementById calls for better readability

**Comment by himanshu-03** [comment]
Is this for chatbot or the script file.
@AKSHITHA-CHILUKA , you will have to open issues for the same, and you can commit it on the same PR no need to create diff prs for this
