### ISSUE TITLE
Feat: Design pulse page

### ISSUE THREAD

**Issue by dhruv8433** [Anushkabh/krishiconnect#679]
### Describe the feature

@Anushkabh 
@RitiChandak 

we can design new route for  `/pulses` page

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/fb35e87f-db8b-4eb1-a0db-bcdd3199c836)

something like this

![image](https://github.com/Anushkabh/krishiconnect/assets/114583978/18c8016c-b435-4132-917f-6e78e3fe68d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
@himanshu-03 

please assign me

**Comment by himanshu-03** [comment]
Hello @dhruv8433 !

please make the changes in your PR first which is already opened #577
