### ISSUE TITLE
Feat: Adding a properly working search in shop.html

### ISSUE THREAD

**Issue by ayush-848** [Anushkabh/krishiconnect#691]
### Describe the feature

Adding a properly working search in shop.html

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/126975547/95315d3b-eb97-43e6-95fb-091bf6c65e84)
in this part

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hey @ayush-848 !

this issue is already opened by someone else on the repo.
Keep looking for more issues in the repo or website.

happy Coding ✨
