### ISSUE TITLE
Feat:Add password visible functionality in login page 

### ISSUE THREAD

**Issue by ANKeshri** [Anushkabh/krishiconnect#696]
### Describe the feature

as in each and every site we see there is password visible functionality so i want to add in this project also

### Add ScreenShots

before : 

![image](https://github.com/Anushkabh/krishiconnect/assets/159682348/94c92d21-df19-40ad-8951-0ff5cdb931f8)
  

want to make it like this 

https://github.com/Anushkabh/krishiconnect/assets/159682348/5d14e606-d9f4-4cd6-8af8-a101ba9aadd7

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@Anushkabh please assign me this issue i want to work on it

**Comment by himanshu-03** [comment]
Hey @ANKeshri !

This issue is too small to  be counted as a contribution.
Keep looking for more issues in the repo and website.

happy coding ✨
