### ISSUE TITLE
Feat:Add hover on cards in section WHY कृषिCONNECT

### ISSUE THREAD

**Issue by zalabhavy** [Anushkabh/krishiconnect#697]
### Describe the feature

I will add hover effects like scale , shadow and make it attractive when hover on it !

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/126322584/eb2944c1-2c13-4f63-8d45-ff192da3ccaa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@himanshu-03 Can you please assign me this task !

**Comment by himanshu-03** [comment]
Hello @zalabhavy !

There is already a hover effect added on it.
Keep looking for more issues in the repo.

happy coding ✨
