### ISSUE TITLE
BUG:Chatbot div is not correctly placed

### ISSUE THREAD

**Issue by YadlaMani** [Anushkabh/krishiconnect#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening chat bot it's very out of place 
![image](https://github.com/Anushkabh/krishiconnect/assets/133841094/d0293884-eb73-40cc-962c-e4b8458d6c92)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @YadlaMani !

You can start working on this issue.

**Comment by YadlaMani** [comment]
@himanshu-03 created pull request check it once if possible increase level
