### ISSUE TITLE
Feat:Enhancing the rate us page

### ISSUE THREAD

**Issue by YadlaMani** [Anushkabh/krishiconnect#701]
### Describe the feature

Would like to improve the rate us page 

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @YadlaMani !

The issue is already been assigned to someone else
Keep looking forr more issues in the repo.

Happy Coding ✨
