### ISSUE TITLE
Feat: adding a new letter section in home page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anushkabh/krishiconnect#703]
### Describe the feature

we take input from the user and send the newsletter 

### Add ScreenShots

here we can add it
![image](https://github.com/Anushkabh/krishiconnect/assets/125277258/0fb97066-5537-4911-b556-13127d1ce039)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
hi @himanshu-03 can i work upon the issue

**Comment by himanshu-03** [comment]
Hey @RamakrushnaBiswal !

I belieeve that the newsletter option is always available in the footer of the website.
Do let me know your view about this!

**Comment by RamakrushnaBiswal** [comment]
Hi @himanshu-03 yes it is looks good

**Comment by himanshu-03** [comment]
> Reference

Will you be also doing the backend part of it or just the frontend design?

**Comment by RamakrushnaBiswal** [comment]
Frontend only for all pages

**Comment by himanshu-03** [comment]
> Frontend only for all pages

Hey @RamakrushnaBiswal !

Creating just the frontend for a newsletter is not our dire need right now.
You can keep looking for other issues in the repo.

happy coding ✨
