### ISSUE TITLE
BUG: Adding form validation in rate us page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anushkabh/krishiconnect#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Anushkabh/krishiconnect/assets/125277258/807b2b91-dbb2-4f88-9622-c4973205403f)
if i didn't enter anything it does not show you need to fil out the field etc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @RamakrushnaBiswal !

The rate us page is currently going many changes as issues were already assigned.
Keep looking more issues in the repo unitl them.
