### ISSUE TITLE
Feat: Adding payment after checkout.

### ISSUE THREAD

**Issue by Upendra2003** [Anushkabh/krishiconnect#71]
### Describe the feature

Adding payment like QR and upi payment will be helpful.

### Add ScreenShots

![Screenshot (486)](https://github.com/Anushkabh/krishiconnect/assets/96371563/e189b968-8be4-4ddd-8e62-2c040ab73cb7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Jamir2412** [comment]
@Upendra2003 can you please assign this issue to me and add gssoc label..?
