### ISSUE TITLE
Feat: Adding Links to the Footer and Changing the Logo in the Footer

### ISSUE THREAD

**Issue by himanshu-03** [Anushkabh/krishiconnect#712]
### Describe the feature

- The logo in the Footer should be replaced with the logo of Header
- We will be having different individual pages for each category, so those must be linked in the footer.
- The FAQ link must be added and connected with the FAQ page in the footer.

### Add ScreenShots

- Logo in Footer (Currently)
    > ![image](https://github.com/Anushkabh/krishiconnect/assets/97957777/9bea6f55-81bf-49df-af18-b0cf4b050dc3)

- Logo in Footer (After doing the mentioned changes should look like)
    > ![image](https://github.com/Anushkabh/krishiconnect/assets/97957777/23c92dce-1a4b-45c0-9b3d-934c9fa0f4fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by himanshu-03** [comment]
This is an open issue. 
Anyone who is interested in working on this issue can comment and tag me on this issue.

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @himanshu-03

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @himanshu-03

**Comment by himanshu-03** [comment]
Hello @AsmitaMishra24 !

You can start working on this issue.
Happy Coding ✨
