### ISSUE TITLE
MAKING THE Image in the Contact section clearer and add some curves on the corner the corner of the blue section.

### ISSUE THREAD

**Issue by ANIRUDH130903** [Anushkabh/krishiconnect#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The image can be made more clearer and the blue headquarters section can be made made with more curves 
![Screenshot 2024-07-01 134245](https://github.com/Anushkabh/krishiconnect/assets/129547564/e4b37874-80d8-40f2-bf91-6c96b6981cfb)

@Anushkabh can please assign me this issue .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hey @ANIRUDH130903 !

This issue is already addressed and assigned to someone else.
keep looking for new issues in the repo.

Happy coding ✨
