### ISSUE TITLE
Feat:CUSTOMIZED SCROLLBAR

### ISSUE THREAD

**Issue by Nih1tGupta** [Anushkabh/krishiconnect#722]
### Describe the feature

Customizing scrollbars is a great way to add a personal touch to your website and make it more user-friendly. By using custom CSS properties, you can control the appearance of your scrollbars and create a more cohesive look and feel for your website

### Add ScreenShots

![scrollbar](https://github.com/Anushkabh/krishiconnect/assets/119615342/7074e357-1a30-4bdc-b661-10b5ae3e77ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @Nih1tGupta !

I dont there is a need for scroll bar itself on the website . We are planning to removee it instead.

Happy Coding ✨
