### ISSUE TITLE
Feat: Add actual colour of social icon on hovering in footer .

### ISSUE THREAD

**Issue by ANKeshri** [Anushkabh/krishiconnect#724]
### Describe the feature

when we hover on social icon in footer it will convert to its original colour .

I am sure that users will definately like this feature  . 

### Add ScreenShots

before : 

https://github.com/Anushkabh/krishiconnect/assets/159682348/7d3761bd-c70c-45f2-8527-cc72d104e28a

want to make it like this : 

https://github.com/Anushkabh/krishiconnect/assets/159682348/6549c4bc-2c8d-4997-a764-83c5e2e1921c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@Anushkabh @himanshu-03 please assign this issue to me under gssoc labels .

**Comment by himanshu-03** [comment]
Hello @ANKeshri !

You can start workinng on this issue. We can keep the socials on the side of the website too right? just like you are showng in your screenshot make sure to add the github logo too.

Happy Coding ✨

**Comment by ANKeshri** [comment]
- @himanshu-03 actually I was telling that at present the social icons in the footer changes to green colour when hovering I want to make it just like it is shown in the above video .
- but if you want that there should be social icon on right of website to i can also do that . 
- please tell me so that i can complete the issue fast . 
- thank you

**Comment by himanshu-03** [comment]
> Author

Yes we can havvee it in the right considering that it doesnt move with the website, ot must always be on the right side irrespective of the page we are in.

**Comment by ANKeshri** [comment]
> > Author
> 
> Yes we can havvee it in the right considering that it doesnt move with the website, ot must always be on the right side irrespective of the page we are in.

sure I am working now thank you
