### ISSUE TITLE
DOC:i want to update server.js

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Anushkabh/krishiconnect#726]
### What's wrong with the existing documentation

to enhance the security and robustness of your application.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @AKSHITHA-CHILUKA !

you can start working on this issue.
Happy Coding ✨
