### ISSUE TITLE
BUG: Error in SHop Section

### ISSUE THREAD

**Issue by katarianikita2003** [Anushkabh/krishiconnect#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In shop section, after discount amount should be less then the original price

![Screenshot 2024-07-01 230856](https://github.com/Anushkabh/krishiconnect/assets/158465309/7c996e8e-26ec-4335-92d2-413aebe1acaf)

Here, after discount, the price is higher than the original price

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @katarianikita2003 !

Currently this is just a mock data, this isnt the original data we are dealing with rn.
Keep looking for more issues in the repo.

Happy Coding ✨
