### ISSUE TITLE
Feat:Making Links in the footer responsive

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Anushkabh/krishiconnect#733]
### Describe the feature

In the footer links arenot responsive when we click on the products there is no response

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/143107589/9641a404-7ff8-479d-add4-fadffa743dcd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@Anushkabh  Please assign me the issue

**Comment by himanshu-03** [comment]
Hello @Saipradyumnagoud !

The issue was already been addressed and s fixed now.
Keep looking for more issues in the repo.

Happy Coding ✨
