### ISSUE TITLE
Feat:Adding FAQs section in the webpage

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Anushkabh/krishiconnect#734]
### Describe the feature

Adding FAQ section in the webpage

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/143107589/ff0e81e9-3bb3-4eb3-850f-c3ba30ffeab5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@Anushkabh  Please assign me the issue

**Comment by himanshu-03** [comment]
Hello @Saipradyumnagoud !

We already have a FAQ page on the website, we need to enhance that first.

**Comment by Saipradyumnagoud** [comment]
> Hello @Saipradyumnagoud !
> 
> We already have a FAQ page on the website, we need to enhance that first.

 Yes i will enhance it

**Comment by Saipradyumnagoud** [comment]
@himanshu-03 Please assign me i wil work with that

**Comment by Saipradyumnagoud** [comment]
it is not linked in the nav bar

**Comment by himanshu-03** [comment]
> it is not linked in the nav bar @himanshu-03

what?

**Comment by himanshu-03** [comment]
You can find the FAQ linkein the footer

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/Anushkabh/krishiconnect/assets/143107589/f737d4b8-f7e3-42fe-bdb0-3afe70e4391d)

**Comment by Saipradyumnagoud** [comment]
No FAQ section in the nav bar
