### ISSUE TITLE
BUG: When we fill details in feedback form and not select rating message shown Please Enter Your Details

### ISSUE THREAD

**Issue by zalabhavy** [Anushkabh/krishiconnect#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we fill message but not fill rating message should be Please select rating.
I will add that message when rating not seleted.
![image](https://github.com/Anushkabh/krishiconnect/assets/126322584/80df6425-ea5c-427b-8747-cd25303a9884)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@himanshu-03 Can you assign me this issue ?

**Comment by himanshu-03** [comment]
Hey @zalabhavy !

We need to change the whole page and it is assigned to someoone else.
Happy Coding ✨
