### ISSUE TITLE
Feat: Add Navbar to Fruits and Vegetables Pages

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anushkabh/krishiconnect#742]
### Describe the feature

I noticed that the Fruits and Vegetables pages currently do not have a navigation bar (navbar). To improve user experience and site navigation, I recommend adding the navbar to these pages.

### Add ScreenShots

![Screenshot 2024-07-02 153919](https://github.com/Anushkabh/krishiconnect/assets/146121869/68e7cc75-6277-410d-9042-3a17eba59ab7)
![Screenshot 2024-07-02 153930](https://github.com/Anushkabh/krishiconnect/assets/146121869/36ed0f8e-7cf2-41e9-bc3e-ac7cb933b613)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @himanshu-03

**Comment by RitiChandak** [comment]
@AsmitaMishra24 This issue already exists

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 This issue already exists

ok..no problem
