### ISSUE TITLE
BUG: Discrepancy in pricing in shopt

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1440" alt="Screenshot 2024-07-02 at 10 03 22 PM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/93be53d6-9850-44b1-bcc4-b03ca5986fb2">
It can be seen the regular price and discount have been interchanged, for which it is showing the price of mint lives is 10 but cut down and showing 41 where it would be the opposite, regular price 41 and 10 discount.

please allow me to fix that issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hello @sahajoydeep !

This is just a mock data right now. We dont need to update live prices right now.
Happy Coding ✨
