### ISSUE TITLE
Feat: Making a functional page for fruits

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anushkabh/krishiconnect#748]
### Describe the feature

- Earlier page of fruits did not look appealing and also , it did not have option to add to cart
- I made a page of fruits , matching the theme of the project along with the functionality of add to cart , making it more user friendly

### Add ScreenShots

Before:

https://github.com/Anushkabh/krishiconnect/assets/162733812/6ade9c10-96d6-42af-b907-ff6644fad010

After:

https://github.com/Anushkabh/krishiconnect/assets/162733812/9a59bafe-f958-4639-bfe8-a2a8d7ee3b9c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@himanshu-03 @RitiChandak I feel , this would look nice , I want to work on it , please assign it to me

**Comment by himanshu-03** [comment]
Great @Maana-Ajmera !

You can start working on this issue.
happy coding ✨

**Comment by Maana-Ajmera** [comment]
@himanshu-03 doing it
