### ISSUE TITLE
Feat: Implement Hover Effect on Social Icons

### ISSUE THREAD

**Issue by HarshadaGirase** [Anushkabh/krishiconnect#749]
### Describe the feature

Add a hover effect to the social media icons on the website to enhance user interaction and provide visual feedback when users hover over the icons. This will improve the overall user experience and make the icons more engaging.

### Add ScreenShots

![krishi](https://github.com/Anushkabh/krishiconnect/assets/128895955/80589cf6-a4d4-4f81-b96b-709132580b7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hello @HarshadaGirase !

Our repo has changed and we dont need a hover effect now. And it is already been addressed by someone else.
Hapy Coding ✨
