### ISSUE TITLE
Feat:  Enhance Copyright Section with Clear Display of Name and Dark Background

### ISSUE THREAD

**Issue by HarshadaGirase** [Anushkabh/krishiconnect#750]
### Describe the feature

Enhance the copyright section in the footer by displaying the name clearly with a contrasting dark background color. This will ensure better visibility and readability, improving the overall aesthetics and user experience.

### Add ScreenShots

![Uploading krishi.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
Kindly assign this issue to me

**Comment by himanshu-03** [comment]
Please provide the screenshot @HarshadaGirase
