### ISSUE TITLE
Feat:  Add Phone Field to Contact Us Page

### ISSUE THREAD

**Issue by HarshadaGirase** [Anushkabh/krishiconnect#751]
### Describe the feature

Enhance the Contact Us page by adding a phone field to collect phone numbers from users. This will provide an additional mode of communication, improving customer service and allowing for more direct contact.

### Add ScreenShots

![phonefield](https://github.com/Anushkabh/krishiconnect/assets/128895955/84c99a8a-cba1-4fa7-8778-e0bc04dddafd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
I would like to work on this issue. Kindly assign to me.

**Comment by himanshu-03** [comment]
We dont need this right now.
