### ISSUE TITLE
BUG: Not Interactive 

### ISSUE THREAD

**Issue by AadiJain06** [Anushkabh/krishiconnect#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an issue in Wishlist view page only the half page is visible on desktop mode assign this issue under gssoc i can fix this issue

![image](https://github.com/Anushkabh/krishiconnect/assets/160418101/8aa4d70c-7246-43d7-94f2-f5467da01d9f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hello @AadiJain06 !

The issue is already fixed.
Happy Coding ✨
