### ISSUE TITLE
Feat: Add a "e-learning" section in the Navbar Menu and make a functional page for it.

### ISSUE THREAD

**Issue by arunimaChintu** [Anushkabh/krishiconnect#755]
### Describe the feature

This will contain all the educational videos about farming and contents related to it.

### Add ScreenShots

<img width="1257" alt="Screenshot 2024-07-03 at 12 11 06 PM" src="https://github.com/Anushkabh/krishiconnect/assets/99474881/2ef5f6ee-bd86-4649-ae33-dd256aa57ea2">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arunimaChintu** [comment]
@Anushkabh Please assign me this issue.

**Comment by himanshu-03** [comment]
Hey @arunimaChintu !

Currently we are not focusing on the e-learning part.
keep looking for more issues in the repo.

Happy coding ✨
