### ISSUE TITLE
Feat: Add a "Contact us" section in Navbar which redirects to the footer ( cause footer contains the contact us details)

### ISSUE THREAD

**Issue by arunimaChintu** [Anushkabh/krishiconnect#756]
### Describe the feature

This adds a "Contact us" section in Navbar which redirects to the footer ( cause footer contains the contact us details).

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/99474881/0be726c6-7114-4f6e-8f89-696b9d40ec27

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
![image](https://github.com/Anushkabh/krishiconnect/assets/97957777/fc146f56-91be-449a-9193-a39108540cab)

We already have a contact uss section in our website.
