### ISSUE TITLE
Feat: Add home tab in the navbar

### ISSUE THREAD

**Issue by JagjeetChauhan** [Anushkabh/krishiconnect#760]
### Describe the feature

As it is very confusing to click on the logo to go to the home page, so adding home tab button in the other pages will be helpful

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/98844703/16bea17f-9213-4098-839f-43bb27a0621e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
hey

I dont think this is necessary right now. We can press on the logo and go to homepage
Keep looking for issues in the repo.
Happy Coding ✨

**Comment by JagjeetChauhan** [comment]
ok
