### ISSUE TITLE
BUG: Scrolling up button moves towards right on hovering  

### ISSUE THREAD

**Issue by H1mang1** [Anushkabh/krishiconnect#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[KrishiConnect.webm](https://github.com/Anushkabh/krishiconnect/assets/123282807/95e8d22e-6c97-4cd6-bbb8-2748dd55a63d)

On hovering bottom to top button it moves towards right . It should stay at the same place as it was before hovering.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi @H1mang1 !

This issue is already  been fixed by someone.
Happy Coding ✨
