### ISSUE TITLE
Feat: Add search option 

### ISSUE THREAD

**Issue by sakshiiiii26** [Anushkabh/krishiconnect#77]
### Describe the feature

By adding search option user can search items directly. Price of every item is same which need to be change and also price should be shown as per kg

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshiiiii26** [comment]
Hello @Anushkabh I'm contributor under GSSoC 24 please assign this task to me!!

**Comment by Hitesh4278** [comment]
Hi @Anushkabh  can you assign this issue to me as I have already worked on this kind of feature?
