### ISSUE TITLE
BUG: The Scroll To Top Button is Only Present in Home Page

### ISSUE THREAD

**Issue by MastanSayyad** [Anushkabh/krishiconnect#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh, @RitiChandak and @himanshu-03

The **scroll to top button** is only present in home page and absent in other pages

I would like to implement the button in all pages to maintain consistency and increase the user experience across the website.
Could you please assign this issue to me under gssoc?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
This issue is already been addrssed
