### ISSUE TITLE
Feat: Make website SEO Friendly

### ISSUE THREAD

**Issue by chaanakyaaM** [Anushkabh/krishiconnect#780]
### Describe the feature

I would like to make the website SEO friendly by adding appropriate meta tags including the descriptions, keywords, author etc.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Sure thing!
You can work on this issue.
