### ISSUE TITLE
Feat:Add custom cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [Anushkabh/krishiconnect#781]
### Describe the feature

I would like to add a custom cursor to the website which improves the overall UI of the website.

### Add ScreenShots

Like this: 

https://github.com/Anushkabh/krishiconnect/assets/131477601/eee70920-7921-4f1c-a7e5-7a1cdf7e1be1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
No, this will make it look morelike a gimmick.
