### ISSUE TITLE
BUG: Correct Footer in FAQ Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anushkabh/krishiconnect#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer on the FAQ page is different from the footer on other pages of the website.
![Screenshot 2024-07-04 143047](https://github.com/Anushkabh/krishiconnect/assets/146121869/d91e7c40-77fd-42c5-a345-bd37f6554847)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
You can work on this issue.
