### ISSUE TITLE
Make the clickable links

### ISSUE THREAD

**Issue by Tanishashrivas** [Anushkabh/krishiconnect#785]
### Describe the feature

In the footer, i would like to make the mail and contact links clickable. Like when the user clicks on the number, it gets copied automatically and when the mail is clicked, user is taken to the mail.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/114223066/e1cc5929-a32d-4d3b-be95-5151e0c01562)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @Tanishashrivas!

CUrrently we dont plan to add our email or address here, so we dont need this right now.
Happy Coding ✨
