### ISSUE TITLE
BUG:  Some Links in Footer are not Redirecting Correctly

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anushkabh/krishiconnect#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Several links in the footer of the website are not redirecting correctly and result in error pages. This issue affects the usability and navigation experience for users.
Example: 
![Screenshot 2024-07-04 154510](https://github.com/Anushkabh/krishiconnect/assets/146121869/cae741be-f169-4837-8c90-85de98e3f619)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Its correct in deployment.
