### ISSUE TITLE
Feat: fix UI issues and images

### ISSUE THREAD

**Issue by 777advait** [Anushkabh/krishiconnect#79]
### Describe the feature

i can spot a few issues on the website regarding the UI i will list them here along with screenshots:
1. navbar logo is not transparent.
2. navbar links are not center aligned
3. bg image in hero section of most pages is stretched
4. /login.html doesnt have navbar
5. contact form on /login.html doesnt look good

### Add ScreenShots

<img width="1148" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/76993204/e4cbbeab-4332-4b18-8986-4ebfcba5f4e4">

<img width="460" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/76993204/8fe8c10e-3f0d-43c0-9dc1-ee9fe71f1098">

<img width="1440" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/76993204/9ff8f34c-fdd9-4fe6-af6e-dca67d4f3092">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@777advait  kindly pull the updated code to avoid merge conflicts
