### ISSUE TITLE
BUG: Use of redundant images

### ISSUE THREAD

**Issue by DevNandini02** [Anushkabh/krishiconnect#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In many sections and pages of the website same images are used. Also images are not put according to the heading specified. Use of different images will make the UI better.

https://github.com/Anushkabh/krishiconnect/assets/124669890/081b1a78-2dee-42d5-99d4-1285656ad5dd

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevNandini02** [comment]
@himanshu-03 sir please assign this task to me.

**Comment by himanshu-03** [comment]
Hey @DevNandini02 !

Currently this is just a mock page.
Happy COding ✨
