### ISSUE TITLE
Feat: Making a page for vegetables including functionalities 

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anushkabh/krishiconnect#791]
### Describe the feature

- Earlier vegetable page didnt match with the theme of our project like shop page
- I made a page of vegetables , matching the theme of the project along with the functionality of add to cart and wishlist , making it more user friendly

### Add ScreenShots

Before:

https://github.com/Anushkabh/krishiconnect/assets/162733812/c42cac5c-b991-44b7-89ba-80c1d881fbf5

After :

https://github.com/Anushkabh/krishiconnect/assets/162733812/f54e89b1-02e0-4fae-8fcc-b288046e6070

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@himanshu-03 I want to work on it , please assign it to me

**Comment by himanshu-03** [comment]
hey @Maana-Ajmera !

you can start working on this issue.
happy coding ✨
