### ISSUE TITLE
BUG: Shop page navbar tabs not visible in light mode

### ISSUE THREAD

**Issue by DevNandini02** [Anushkabh/krishiconnect#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we scroll down in the shop page, the navbar is becoming white completely, navbar tabs are only visible on hovering.

https://github.com/Anushkabh/krishiconnect/assets/124669890/869ba19b-6c87-4566-ae20-2af17fc69993

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @DevNandini02 !

We need to fix the whole navbar and it is been worked on.
