### ISSUE TITLE
BUG: Navbar tabs and icons not aligned properly in many pages

### ISSUE THREAD

**Issue by DevNandini02** [Anushkabh/krishiconnect#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar tabs and icons are not properly aligned in many pages of the website. Also the length of the navbar is varying in different pages.

![krishi_bug2](https://github.com/Anushkabh/krishiconnect/assets/124669890/38869af7-3238-4e7c-a9b5-e4fb709b58b5)
 
![krishi_bug1](https://github.com/Anushkabh/krishiconnect/assets/124669890/f599529c-3357-46db-bb20-ee1f850d05a2)

It should like the image below in every page

![image](https://github.com/Anushkabh/krishiconnect/assets/124669890/cb0d3037-eff7-4f14-a4cf-66baa923ba87)

The navbar should look same in each page of the website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hey @DevNandini02 !

Thisissue is already been addressed

Happy Coding ✨
