### ISSUE TITLE
Feat: Add login and signup feature to the website

### ISSUE THREAD

**Issue by DevNandini02** [Anushkabh/krishiconnect#796]
### Describe the feature

There should be a login and signup option in the website which is an essential feature in such kind of shopping websites where people  could log in into their own accounts and buy products.

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/124669890/8cf041e3-ca20-4bf7-a576-47eae3633c0b

I can create such kind of functionality and interface in login and signup pages.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevNandini02** [comment]
@himanshu-03 sir please assign this task to me.

**Comment by RitiChandak** [comment]
#547
