### ISSUE TITLE
BUG: No dark mode in FAQ 

### ISSUE THREAD

**Issue by root-0101** [Anushkabh/krishiconnect#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no dark mode in FAQ section

![Screenshot 2024-07-04 194957](https://github.com/Anushkabh/krishiconnect/assets/142779809/79106a8f-7a1e-45fc-be16-0c6b2bf80c00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#793
