### ISSUE TITLE
Feat: Want to add error 404 page not found 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Anushkabh/krishiconnect#814]
### Describe the feature

I am thinking of adding an error 404 page which will be shown on entering any unwanted url 
With the implementation of that this will solve the Error showing after entering unwanted url 

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/118350936/c84e5212-ed1a-4f17-8c6a-f2bbd7e07503

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#641
