### ISSUE TITLE
Feat: Implementation of dark mode for contact and faq page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Anushkabh/krishiconnect#817]
### Describe the feature

I want to implement the dark mode for these two pages
As i don't know whether it is a bug or the mode is not implemented yet because when i am changing the mode the mode is not changing so i want to implement the mode for that 

### Add ScreenShots

https://github.com/Anushkabh/krishiconnect/assets/118350936/637848ba-7091-406a-ab26-5fc823d7ee98

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#598 #793
