### ISSUE TITLE
Adding  social media icons

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Anushkabh/krishiconnect#823]
### Describe the feature

Adding other social media icons on the footer section , such as discord , github, linkedin etc:- to enhance the reach of ur website and also to increase ur connections.

### Add ScreenShots

![Screenshot 2024-07-05 012555](https://github.com/Anushkabh/krishiconnect/assets/117037441/bc9c3acd-ced4-431f-b96d-69b2afe97e6a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@Anushkabh kindly assign me this issue under gssoc'24

**Comment by Soumya6Tiwari** [comment]
@himanshu-03  you only suggest the icons to be added as github , linkedin , discord are among the common ones.

**Comment by RitiChandak** [comment]
![image](https://github.com/Anushkabh/krishiconnect/assets/96969496/47d6d818-2099-48a8-85bf-085a283923df)
