### ISSUE TITLE
BUG:Text is not visible in the footer of MyCart page.

### ISSUE THREAD

**Issue by meetarora10** [Anushkabh/krishiconnect#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Text is not visible properly in the footer of Cart page.
Kindly assign this task to me an I can fix this issue and add more styling to the text and to the button on the footer.
![Screenshot (622)](https://github.com/Anushkabh/krishiconnect/assets/143121854/97569249-60f9-48cc-aba8-ed2e85a2324d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#807
