### ISSUE TITLE
Add Legal Information to the Footer

### ISSUE THREAD

**Issue by lovelymahor** [Anushkabh/krishiconnect#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to add legal information to the footer of the website to ensure compliance with regulations and to provide transparency to our users. This information should include links to our privacy policy, terms of service, and any other relevant legal documents.

### Screenshot

![Screenshot (223)](https://github.com/Anushkabh/krishiconnect/assets/141830010/40c00c94-41d1-4300-b812-b81dd7d52754)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
@Anushkabh, please assign it to me I want to work on this
Also, please add the labels gssoc and the level which you find appropriate for this issue. thank you!

**Comment by RitiChandak** [comment]
#674
