### ISSUE TITLE
Adding Hovering Effect to website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Anushkabh/krishiconnect#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Adding hovering effect makes the website appealing good

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuhainaFathimaM** [comment]
Assign this issue as GSSoC'24 .. 
I would like to work on this issue..
@Anushkabh   Please assign me this issue

**Comment by vaishnavip27** [comment]
Hey @Anushkabh I would like to work on this issue. Please assign it to me. Looking forward for your approval

**Comment by himanshu-03** [comment]
Fixed in #266
