### ISSUE TITLE
Feat: Hover Effect of Transition & Transform On Cards Section

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#86]
### Describe the feature

Hi @Anushkabh while working on the #37 issue, I tried that if I add a hover effect, I transition and transform where I tilt the cards just by 5px, the animation and hover effect look really good.

So, when users hover over the Cards Sections -- Oil Seeds, Herbs, Pulses etc, when they hover over the text changes as per the #37 issue, but when they hover over the cards, I want the cards to pop up a bit, realizing the user, that they are on Oil Seeds Card index or etc.

Please assign me this task.

### Add ScreenShots

Before --

<img width="1424" alt="Screenshot 2024-05-13 at 2 36 46 AM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/8ae59d96-5a3e-4dfa-b2d2-cf44bb18b46d">

After --
<img width="1440" alt="Screenshot 2024-05-13 at 2 37 58 AM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/f3eea0cc-a0af-42a1-b741-ec0c1e8168f9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by sahajoydeep** [comment]
@himanshu-03 hey the section that I raised the issue, is not there, how can I work on the issue?
