### ISSUE TITLE
BUG: hamburger icon needs to replace with close icon 

### ISSUE THREAD

**Issue by kapilG0** [Anushkabh/krishiconnect#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240710_234606](https://github.com/Anushkabh/krishiconnect/assets/59639410/952116e3-c3a4-4fca-87da-7c81418b2241)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @Anushkabh please assign this issue to me under gssoc 24

**Comment by shivansh84ya** [comment]
hey @kapilG0  
Successfully fixed issue #862 by updating the navbar icon and implemented sticky navbar across all pages (#856).
