### ISSUE TITLE
BUG: Clicking mail does not redirect to gmail.

### ISSUE THREAD

**Issue by Madhavan112** [Anushkabh/krishiconnect#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I like to work on this feature and moreover i want to fix the UI to page colour instead of random blue colour and add little spacing.
Please assign me this task as soon as possible under gssoc 2024.
![Capture](https://github.com/user-attachments/assets/142a58b6-3dfc-4fa3-a285-3c350fbca203)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshulagr5** [comment]
@Anushkabh I would like to work on this issue. Kindly assign it to me.
