### ISSUE TITLE
Feat: FAQ page is not displaying the answers.

### ISSUE THREAD

**Issue by Hemashree21** [Anushkabh/krishiconnect#905]
### Describe the feature

The FAQ page UI is messed up and for some of the questions, answers cannot be viewed.
@Anushkabh can you please assign this to me?

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c1346060-9274-40c8-b53f-e43b0b1919a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ansh101112** [comment]
@Hemashree21 @Anushkabh I have a ready PR regarding this issue kindly assign me this issue.
