### ISSUE TITLE
Feat: Making a page for oil seeds including functionalities

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anushkabh/krishiconnect#909]
### Describe the feature

- I made a page of oil seeds , matching the theme of the project along with the functionality of add to cart and wishlist , making it more user friendly

### Add ScreenShots

Similar to 

https://github.com/Anushkabh/krishiconnect/assets/162733812/f54e89b1-02e0-4fae-8fcc-b288046e6070

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@RitiChandak Please assign it to me

**Comment by RitiChandak** [comment]
The oil seed page is already there.
