### ISSUE TITLE
Feat: Making FAQ page

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anushkabh/krishiconnect#910]
### Describe the feature

Currently there is no FAQ page in the website , I want to make a FAQ page for our website

### Add ScreenShots

https://github.com/user-attachments/assets/befa982c-f3a2-4dac-980e-3a8c88a1e716

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@RitiChandak Please assign it to me

**Comment by RitiChandak** [comment]
FAQ page is already there
