### ISSUE TITLE
BUG:issue in icon hover effect 

### ISSUE THREAD

**Issue by Varsani2520** [Anushkabh/krishiconnect#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in footer when i hover on the social media icon then disable or fully white display

![image](https://github.com/user-attachments/assets/330d59b2-5fba-4af1-880f-a13116e2f2c3)

we can in hover effect display like actual icons 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@RitiChandak ,assign me

**Comment by RitiChandak** [comment]
check it for all the other pages
