### ISSUE TITLE
Improve the Transaction page

### ISSUE THREAD

**Issue by Sneha123-zudo** [Anushkabh/krishiconnect#94]
### Describe the feature

I want to improve the transaction page of the website. As it's UI is not looking good. I can add more contents and elements to it.

### Add ScreenShots

<img width="223" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/145490348/22843f55-d43f-40c0-a2aa-03b63b1c515a">

By adding this content , in transaction page.
Please assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tushant-akar** [comment]
@Anushkabh Pls assign this issue to me.
