### ISSUE TITLE
Making More Attractive Change

### ISSUE THREAD

**Issue by gupta-ritik** [Anushkabh/krishiconnect#97]
### Describe the feature

the following changes are required.
1. Farmer Login Page
2. Addition of the FAQs section
3. Footer Styling
4. Hover Effect updation
5. Navbar Updation
6. Testiminol

### Add ScreenShots

![Screenshot 2024-05-14 022123](https://github.com/Anushkabh/krishiconnect/assets/127002992/e15e4c13-b98b-4abe-a387-4ea819b3d44a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@gupta-ritik  start with farmer login page
